export type CountryRecruitmentGuide = {
  slug: string;
  seoTitle: string;
  seoDescription: string;
  overview: string;
  recruitmentFocus: string;
  workRoute: string;
  jobKeys: string[];
  candidateRequirements: string[];
  documentFocus: string[];
  languageLicensing: string;
  employmentNotes: string;
  arrivalPreparation: string;
};

const guide = (value: CountryRecruitmentGuide) => value;

export const COUNTRY_RECRUITMENT_GUIDES: CountryRecruitmentGuide[] = [
  guide({
    slug: "united-states",
    seoTitle: "USA Jobs & Recruitment Guide 2026 | Work Visa Careers",
    seoDescription: "Explore United States recruitment opportunities, common jobs, employer sponsorship pathways, visa process guidance, candidate requirements and application support with Red Stone Employment Agency.",
    overview: "The United States has a large and highly varied labour market. International recruitment can range from temporary agricultural or seasonal work to healthcare, technology, hospitality and specialist professional employment. The correct route depends on the employer, occupation, visa classification and applicant eligibility.",
    recruitmentFocus: "Red Stone candidates should apply only to genuine vacancies where an employer is prepared to follow the lawful U.S. recruitment and petition process. Temporary worker programmes and employment-based immigration categories have different rules, timelines and employer obligations.",
    workRoute: "For many employer-sponsored jobs, the employer first completes the required U.S. labour or petition stage. After an approval or qualifying petition, the candidate may proceed to the appropriate visa application, interview, medical or document stage where required. A visa does not itself guarantee admission at the U.S. border.",
    jobKeys: ["nanny", "security", "housekeeper", "caregiver", "farm-worker", "hotel", "cook", "it-support", "software", "engineer"],
    candidateRequirements: ["Valid passport and consistent identity records", "CV matched to the vacancy and genuine work history", "Employer-required experience, qualifications or licences", "Background or police checks where required", "Ability to meet the specific U.S. visa classification rules"],
    documentFocus: ["Passport", "CV / resume", "Education and trade certificates", "Employment references", "Employer petition or offer documents", "Police or medical records only when requested for the route"],
    languageLicensing: "English ability is important for most workplaces. Regulated occupations such as nursing and some trades require state-level licensing or credential recognition before practice.",
    employmentNotes: "Pay, benefits, overtime and employment conditions vary by state, employer and occupation. Candidates should rely on the written offer and applicable U.S. employment rules rather than general salary advertisements.",
    arrivalPreparation: "Before travel, confirm the employer address, reporting instructions, accommodation arrangements where provided, emergency contacts, visa documentation and any port-of-entry documents requested for the specific category."
  }),
  guide({
    slug: "canada",
    seoTitle: "Canada Jobs & Recruitment Guide 2026 | Work Permit Careers",
    seoDescription: "Detailed Canada recruitment guide covering jobs, employer-supported work permits, LMIA and exempt pathways, documents, medicals, candidate preparation and Red Stone applications.",
    overview: "Canada recruits both skilled and entry-level workers across provinces and territories. Opportunities can include healthcare, hospitality, agriculture, logistics, construction, transport, trades and technical services, but eligibility depends on the employer, province, occupation and immigration programme.",
    recruitmentFocus: "A Canadian job opportunity should be assessed together with the employer's ability to hire a foreign worker and the candidate's work-permit eligibility. Some roles may use an LMIA-supported process while others may qualify for an LMIA-exempt route or a separate economic immigration pathway.",
    workRoute: "A typical employer-specific route involves a genuine job offer, the employer's required labour-market or exemption steps, a work-permit application, biometrics and medical examination where applicable, followed by a decision from Immigration, Refugees and Citizenship Canada. Provincial requirements can also apply.",
    jobKeys: ["housekeeper", "cleaner", "warehouse", "farm-worker", "truck-driver", "caregiver", "healthcare-assistant", "nurse", "construction", "welder"],
    candidateRequirements: ["Valid passport", "Accurate CV and work history", "Qualifications or trade evidence relevant to the job", "Language ability appropriate to the occupation", "Work-permit admissibility and medical or police checks where required"],
    documentFocus: ["Passport", "CV", "Job offer or contract", "Employer / LMIA or exemption documents where applicable", "Education or trade certificates", "Biometrics and medical instructions when issued"],
    languageLicensing: "English and/or French ability may be relevant depending on the province and job. Regulated healthcare and trade occupations may require provincial registration, credential recognition or licence conversion.",
    employmentNotes: "Minimum wages, overtime rules and employment standards differ by province. Final salary, accommodation and benefits should be confirmed in the employer's written offer.",
    arrivalPreparation: "Carry the required immigration documents, employer contact details and accommodation information. Some work permits are issued or finalized at entry depending on the approved process, so candidates should follow the instructions in their official decision documents."
  }),
  guide({
    slug: "uae",
    seoTitle: "UAE Jobs & Recruitment Guide 2026 | Dubai & Abu Dhabi Work Visa",
    seoDescription: "Explore UAE jobs, Dubai and Abu Dhabi recruitment, employer work visa and residence process, medical requirements, documents and candidate guidance from Red Stone.",
    overview: "The United Arab Emirates is a major Gulf employment destination with opportunities in hospitality, security, facilities management, construction, retail, logistics, driving, domestic support, healthcare and technical services.",
    recruitmentFocus: "Most foreign employees work through an employer-sponsored labour and residence process. Candidates should verify the exact employer, job title, salary, accommodation, food or allowance arrangements, duty hours and contract before deployment.",
    workRoute: "For standard employment, the employer normally begins the work-permit or entry process. After entry or approval, medical fitness testing, Emirates ID biometrics and residence formalities are completed as required by the relevant federal or emirate authority.",
    jobKeys: ["security", "housekeeper", "cleaner", "warehouse", "delivery-driver", "truck-driver", "hotel", "waiter", "cook", "construction", "technician"],
    candidateRequirements: ["Valid passport", "Employer-approved CV and experience", "Police or conduct records where requested", "Medical fitness for the role and residence process", "Trade or professional credentials for regulated jobs"],
    documentFocus: ["Passport", "Passport photographs where requested", "Signed offer / contract", "Education or trade certificates", "Employer entry / work permit documents", "Medical and Emirates ID documentation"],
    languageLicensing: "English is widely used in many workplaces; Arabic can be useful. Healthcare and certain technical professions require UAE professional licensing or qualification verification.",
    employmentNotes: "Employment packages vary significantly. Candidates should distinguish basic salary from allowances and confirm whether accommodation, transport, food, insurance and air tickets are included in writing.",
    arrivalPreparation: "Keep sponsor contacts, entry permit details, accommodation address and medical or biometric appointment instructions available. Do not hand over original documents except where a lawful procedure requires temporary processing."
  }),
  guide({
    slug: "qatar",
    seoTitle: "Qatar Jobs & Recruitment Guide 2026 | Work Visa & Residence",
    seoDescription: "Detailed Qatar recruitment guide for jobs, employer sponsorship, work visa and residence permit process, medicals, biometrics, documents and Red Stone applications.",
    overview: "Qatar recruits international workers in security, hospitality, facilities, logistics, construction, driving, domestic services, healthcare and technical operations. Most employment is connected to an employer or sponsor-led residence process.",
    recruitmentFocus: "Candidates should verify the employer, job title, salary and benefits before accepting a Qatar placement. Accommodation, food, transport and ticket arrangements should be clearly stated in the contract or official offer.",
    workRoute: "An employer normally initiates the work-entry or sponsorship process. After the required approval and entry steps, the worker may complete medical examination, biometrics and Qatar ID / residence permit procedures under the sponsor's coordination.",
    jobKeys: ["security", "housekeeper", "cleaner", "warehouse", "driver-delivery", "truck-driver", "hotel", "waiter", "cook", "construction", "technician"].map((key) => key === "driver-delivery" ? "delivery-driver" : key),
    candidateRequirements: ["Valid passport", "Employer-matched CV", "Required experience or trade skill", "Medical fitness and biometric compliance", "Background or police documents where requested"],
    documentFocus: ["Passport", "Employment contract", "Employer sponsorship / entry documents", "Certificates where required", "Medical records generated through the approved process", "Biometric and residence documentation"],
    languageLicensing: "English is common in many international workplaces and Arabic is an advantage. Healthcare and specialist occupations may require professional licensing in Qatar.",
    employmentNotes: "The written contract should be checked for salary, overtime, duty hours, rest days, accommodation, food, transport, insurance and return-ticket terms.",
    arrivalPreparation: "Travel only after the correct entry authorization is confirmed. Keep the sponsor's contact details, workplace reporting point and accommodation information available on arrival."
  }),
  guide({
    slug: "kuwait",
    seoTitle: "Kuwait Jobs & Recruitment Guide 2026 | Work Residence Visa",
    seoDescription: "Explore Kuwait jobs, private-sector work residence, domestic and professional recruitment, medicals, documentation and visa process guidance with Red Stone.",
    overview: "Kuwait employs international workers in hospitality, retail, construction, logistics, security, domestic support, driving, healthcare and technical trades. Employment residence categories are generally sponsor-based.",
    recruitmentFocus: "Private-sector employment commonly uses the Article 18 work-residence framework, while other residence categories apply to government, domestic and family cases. The exact route depends on the employer and job.",
    workRoute: "The sponsor typically initiates the work authorization and entry process. Medical, police or security checks and residence formalities may be required before or after arrival according to the applicable category.",
    jobKeys: ["security", "housekeeper", "cleaner", "warehouse", "delivery-driver", "hotel", "waiter", "cook", "construction", "electrician", "plumber"],
    candidateRequirements: ["Valid passport", "Genuine employer offer", "Relevant work experience", "Medical fitness", "Required trade or professional documents"],
    documentFocus: ["Passport", "Offer / employment contract", "Sponsor authorization documents", "Education or trade records", "Police and medical documents where required", "Residence-processing records"],
    languageLicensing: "Arabic can be useful, while English is common in many private-sector workplaces. Regulated professions may require local recognition or licensing.",
    employmentNotes: "Candidates should review salary, housing, meals, transport, working hours and leave terms before signing. Benefits should not be assumed unless stated in writing.",
    arrivalPreparation: "Confirm sponsor details, authorized entry documents and the residence-processing schedule before travel. Keep copies of the signed contract and receipts for any lawful candidate-paid services."
  }),
  guide({
    slug: "bahrain",
    seoTitle: "Bahrain Jobs & Recruitment Guide 2026 | LMRA Work Permit",
    seoDescription: "Bahrain recruitment guide covering jobs, LMRA employer work permits, residence, documents, medical requirements and international candidate preparation.",
    overview: "Bahrain's international workforce supports hospitality, retail, construction, facilities, logistics, food service, healthcare and technical industries. Foreign employment is commonly linked to an employer work permit managed through Bahrain's labour and immigration authorities.",
    recruitmentFocus: "The employer and job must be genuine and compatible with the applicable Labour Market Regulatory Authority process. Visit status should not be treated as permission to work.",
    workRoute: "A qualifying employer generally begins the LMRA work-permit process. Entry, medical and residence or identity procedures then follow according to the worker's approved status and official instructions.",
    jobKeys: ["housekeeper", "cleaner", "security", "warehouse", "hotel", "waiter", "cook", "construction", "electrician", "technician"],
    candidateRequirements: ["Valid passport", "Employer-selected profile", "Relevant experience", "Medical fitness", "Professional or trade credentials where applicable"],
    documentFocus: ["Passport", "Employment offer", "LMRA / employer permit records", "Certificates", "Medical documents", "Residence and identity documents"],
    languageLicensing: "English is common in many workplaces, with Arabic helpful for customer-facing roles. Professional licensing can apply in healthcare and specialist occupations.",
    employmentNotes: "Review the total employment package, not only headline salary. Housing, transport, meals, insurance and air-ticket terms differ by employer.",
    arrivalPreparation: "Know the sponsor, workplace, accommodation and permit status before departure. Follow only the medical and residence instructions connected to the approved employment case."
  }),
  guide({
    slug: "oman",
    seoTitle: "Oman Jobs & Recruitment Guide 2026 | Employment Visa Process",
    seoDescription: "Explore Oman employment opportunities, employer-sponsored work visa and residence process, medicals, documents, jobs and candidate guidance from Red Stone.",
    overview: "Oman employs foreign workers in construction, hospitality, logistics, facilities, driving, retail, domestic support, healthcare and technical fields. Recruitment must also reflect Oman's occupation and workforce-nationalization rules.",
    recruitmentFocus: "International hiring is employer-led and some occupations may be restricted or subject to changing Omanisation requirements. Candidates should apply only to vacancies confirmed as open to foreign recruitment.",
    workRoute: "The employer normally secures the required labour approval and employment entry authorization. Medical, residence-card and other formalities follow according to official instructions.",
    jobKeys: ["housekeeper", "cleaner", "security", "warehouse", "truck-driver", "hotel", "cook", "construction", "electrician", "mechanic", "technician"],
    candidateRequirements: ["Valid passport", "Employer-approved experience", "Medical fitness", "Trade or education certificates where relevant", "Eligibility for the occupation under current Oman labour rules"],
    documentFocus: ["Passport", "Employment contract", "Employer labour / visa authorization", "Certificates", "Medical records", "Residence-card documents"],
    languageLicensing: "Arabic is useful and English is widely used in many private-sector jobs. Regulated professional roles may require credential verification or local licensing.",
    employmentNotes: "Confirm salary, accommodation, transport, meals, overtime and leave in the written contract. Job titles should match the authorized employment documentation.",
    arrivalPreparation: "Carry sponsor and accommodation details and follow the official residence-card process after arrival. Do not work outside the authorized employer or occupation unless lawfully permitted."
  }),
  guide({
    slug: "australia",
    seoTitle: "Australia Jobs & Recruitment Guide 2026 | Sponsored Work Visas",
    seoDescription: "Advanced Australia recruitment guide covering jobs, employer-sponsored work visas, skills requirements, medicals, English, licensing and Red Stone applications.",
    overview: "Australia's labour market includes healthcare, aged care, construction, agriculture, hospitality, logistics, trades, technology and professional services. International recruitment is strongly linked to occupation eligibility, employer sponsorship rules, qualifications and English-language standards.",
    recruitmentFocus: "Candidates should match their experience to a genuine role and then confirm whether the employer can use an appropriate temporary or permanent skilled pathway. Some occupations require formal skills assessment or registration.",
    workRoute: "Employer-sponsored pathways typically require an eligible employer, nominated occupation and visa application. Health, character, English and skills requirements vary by subclass. Other skilled or regional migration programmes may follow different selection rules.",
    jobKeys: ["cleaner", "caregiver", "healthcare-assistant", "nurse", "warehouse", "farm-worker", "construction", "truck-driver", "electrician", "welder", "software", "engineer"],
    candidateRequirements: ["Valid passport", "Relevant qualifications and work experience", "English ability where required", "Health and character requirements", "Skills assessment or professional registration where applicable"],
    documentFocus: ["Passport", "Detailed CV", "Employment references", "Qualification certificates and transcripts", "Skills assessment / registration evidence where required", "Employer nomination and visa records"],
    languageLicensing: "English requirements can be formal visa or professional-registration conditions. Nurses, electricians and other regulated professions may require Australian registration or licensing.",
    employmentNotes: "Australian awards, enterprise agreements and employment law can affect pay and conditions. Candidates should verify the occupation, salary and employer sponsorship terms in the written offer.",
    arrivalPreparation: "Confirm visa grant conditions, employer reporting instructions, accommodation plan and any local licence-conversion steps before beginning work."
  }),
  guide({
    slug: "new-zealand",
    seoTitle: "New Zealand Jobs & Recruitment Guide 2026 | Accredited Employer Work Visa",
    seoDescription: "Explore New Zealand jobs, accredited employer work routes, candidate requirements, medicals, police checks, skills and Red Stone recruitment guidance.",
    overview: "New Zealand recruits international workers across agriculture, aged care, hospitality, construction, logistics, transport, trades and selected professional sectors. Employer accreditation and job-specific immigration settings can affect eligibility.",
    recruitmentFocus: "A genuine job with an employer permitted to recruit migrants is central to many work routes. Candidates should confirm the role, pay, hours, location and whether qualifications or occupational registration are required.",
    workRoute: "For employer-linked work visas, the employer completes the relevant accreditation and job steps before or alongside the worker's application. Medical, police, experience and qualification evidence may be required depending on the case.",
    jobKeys: ["cleaner", "caregiver", "healthcare-assistant", "nurse", "warehouse", "farm-worker", "horticulture", "truck-driver", "construction", "welder", "cook"],
    candidateRequirements: ["Valid passport", "Job-relevant experience", "Qualifications where required", "Health and character compliance", "Registration or licence eligibility for regulated roles"],
    documentFocus: ["Passport", "CV", "Employment references", "Job offer and employment agreement", "Qualifications", "Medical / police records when officially requested"],
    languageLicensing: "English ability is important across most workplaces. Healthcare and certain trades may require New Zealand registration, licensing or qualification recognition.",
    employmentNotes: "Pay and working conditions must follow New Zealand employment law and the written agreement. Farm and seasonal roles may include roster or accommodation arrangements that should be checked carefully.",
    arrivalPreparation: "Review visa conditions, employer contact details, workplace location, accommodation and any IRD, banking or local onboarding steps provided after arrival."
  }),
  guide({
    slug: "chile",
    seoTitle: "Chile Jobs & Recruitment Guide 2026 | Work & Residence Process",
    seoDescription: "Explore Chile recruitment, jobs, temporary residence and work authorization guidance, documents, Spanish requirements and Red Stone candidate support.",
    overview: "Chile offers employment opportunities in agriculture, food production, hospitality, logistics, construction, mining-related services and technical occupations. International candidates should pay close attention to Spanish-language ability and the residence category that permits work.",
    recruitmentFocus: "A written job offer or employment basis can support certain residence processes, but the correct immigration category must be confirmed before work begins. Job availability for foreign candidates depends on current employer demand.",
    workRoute: "Applicants generally need the appropriate temporary residence or authorization for their employment situation. Immigration documentation, identity records and employer documents must be prepared according to Chilean authority requirements.",
    jobKeys: ["farm-worker", "horticulture", "factory", "food-production", "warehouse", "hotel", "cook", "construction", "mechanic", "technician"],
    candidateRequirements: ["Valid passport", "Spanish ability appropriate to the role", "Employer offer where required", "Qualifications for skilled roles", "Immigration and background documents required by the route"],
    documentFocus: ["Passport", "CV", "Employment offer / contract", "Police and civil-status records where requested", "Qualifications", "Residence-application records"],
    languageLicensing: "Spanish is important for most workplaces. Professional recognition may be necessary for regulated or licensed occupations.",
    employmentNotes: "Candidates should understand salary in local currency, working hours, social-security deductions and whether accommodation or relocation support is included.",
    arrivalPreparation: "Prepare for local identity, tax and employment registration steps after the correct residence status is granted."
  }),
  guide({
    slug: "peru",
    seoTitle: "Peru Jobs & Recruitment Guide 2026 | Work Residence Guidance",
    seoDescription: "Detailed Peru recruitment guide covering international jobs, work and residence process, Spanish, candidate documents and Red Stone application support.",
    overview: "Peru's labour market includes agriculture, food processing, hospitality, logistics, construction, mining services, retail and technical occupations. Foreign workers normally need a residence or immigration status compatible with employment.",
    recruitmentFocus: "Candidates should secure a genuine employer opportunity and understand whether the contract and immigration status meet local requirements before starting work.",
    workRoute: "Employment-based residence or status changes can involve an approved employment contract and immigration application. The exact process depends on the candidate's nationality, current status and job arrangement.",
    jobKeys: ["farm-worker", "food-production", "factory", "warehouse", "hotel", "waiter", "cook", "construction", "mechanic", "technician"],
    candidateRequirements: ["Valid passport", "Spanish communication ability", "Genuine employment basis", "Relevant skill or experience", "Required background and civil records"],
    documentFocus: ["Passport", "CV", "Employment contract", "Police / civil records where required", "Qualifications", "Immigration application records"],
    languageLicensing: "Spanish is generally important for everyday work and administration. Regulated professions may require recognition of foreign qualifications.",
    employmentNotes: "Review the contract for salary, benefits, deductions and social-security arrangements. Employer-provided accommodation should be confirmed explicitly where offered.",
    arrivalPreparation: "Plan for local immigration-card, tax and employment registration steps once the correct status is approved."
  }),
  guide({
    slug: "singapore",
    seoTitle: "Singapore Jobs & Recruitment Guide 2026 | Work Pass Process",
    seoDescription: "Explore Singapore recruitment, Employment Pass, S Pass and Work Permit pathways, jobs, candidate qualifications, documents and Red Stone guidance.",
    overview: "Singapore uses clearly defined work-pass categories for different skill and salary levels. International recruitment includes technology, engineering, hospitality, logistics, food production, construction, marine, healthcare and service-sector roles subject to employer quotas and pass rules.",
    recruitmentFocus: "The employer normally determines the appropriate work pass and submits the application. Candidates should not assume that a job title alone qualifies for a pass; salary, qualifications, sector, employer quota and regulatory criteria matter.",
    workRoute: "An employer or authorized employment agent generally applies for the relevant Employment Pass, S Pass or Work Permit. Medical examinations, security requirements, issuance appointments and identity-card steps depend on the pass category.",
    jobKeys: ["warehouse", "factory", "food-production", "hotel", "waiter", "cook", "construction", "technician", "it-support", "software", "engineer", "nurse"],
    candidateRequirements: ["Valid passport", "Employer-selected role", "Qualifications and experience appropriate to the pass", "Medical fitness where required", "Professional registration for regulated occupations"],
    documentFocus: ["Passport", "CV", "Qualification certificates", "Employer offer", "Work-pass application records", "Medical or registration documents where applicable"],
    languageLicensing: "English is a primary workplace language. Regulated healthcare and certain technical occupations require approval from the relevant Singapore professional authority.",
    employmentNotes: "Work-pass conditions are tied closely to the employer and approved occupation. Accommodation and levy arrangements differ between professional passes and Work Permit sectors.",
    arrivalPreparation: "Follow the In-Principle Approval and issuance instructions carefully, including medical, address and fingerprint/photo appointments where required."
  }),
  guide({
    slug: "united-kingdom",
    seoTitle: "UK Jobs & Recruitment Guide 2026 | Skilled Worker Visa Careers",
    seoDescription: "Detailed UK recruitment guide covering Skilled Worker and Health and Care routes, jobs, sponsor requirements, English, documents and Red Stone applications.",
    overview: "The United Kingdom recruits international workers in healthcare, care, hospitality, construction, engineering, logistics, technology and other eligible occupations. Most long-term employment routes depend on a licensed sponsor and a job that meets the current immigration requirements.",
    recruitmentFocus: "Candidates should verify that the employer is appropriately licensed where sponsorship is required and that the role, salary and occupation code meet the current visa rules. A job advertisement alone is not evidence of sponsorship eligibility.",
    workRoute: "For many sponsored workers, the employer assigns a Certificate of Sponsorship after selection. The candidate then applies for the relevant work visa, provides identity, English, financial, medical or criminal-record evidence where required, and waits for a Home Office decision.",
    jobKeys: ["caregiver", "healthcare-assistant", "nurse", "hotel", "cook", "warehouse", "construction", "electrician", "it-support", "software", "engineer"],
    candidateRequirements: ["Valid passport", "Licensed sponsor where required", "Role meeting current visa criteria", "English-language compliance", "Qualifications, registration and criminal-record checks where applicable"],
    documentFocus: ["Passport", "Certificate of Sponsorship details", "CV and references", "Qualification / professional registration", "English evidence", "TB or criminal-record documents where required"],
    languageLicensing: "English can be a formal immigration and professional requirement. Nurses and other regulated professionals must meet the relevant UK registration standards.",
    employmentNotes: "Salary thresholds and eligible occupations can change. Candidates should use the latest official rules and the exact salary stated by the sponsoring employer.",
    arrivalPreparation: "Check visa conditions, sponsor reporting instructions, accommodation, right-to-work documentation and any eVisa / immigration-status access steps before starting employment."
  }),
  guide({
    slug: "germany",
    seoTitle: "Germany Jobs & Recruitment Guide 2026 | Skilled Worker & Opportunity Routes",
    seoDescription: "Explore Germany jobs, skilled worker recruitment, EU Blue Card and employment visa routes, qualification recognition, German language and Red Stone guidance.",
    overview: "Germany recruits international talent in healthcare, engineering, IT, manufacturing, logistics, hospitality, construction and skilled trades. Qualification recognition and German-language ability are particularly important in many occupations.",
    recruitmentFocus: "Candidates should determine whether their qualification is recognized, comparable or requires formal recognition. Employer-sponsored work, skilled-worker residence and EU Blue Card routes have different qualification and salary conditions.",
    workRoute: "After securing an eligible job or qualifying for another employment route, the candidate normally completes the appropriate national visa or residence application. Recognition, Federal Employment Agency approval, language evidence or professional licensing may be part of the process.",
    jobKeys: ["nurse", "healthcare-assistant", "warehouse", "factory", "construction", "electrician", "plumber", "welder", "mechanic", "it-support", "software", "engineer", "hotel"],
    candidateRequirements: ["Valid passport", "Recognized or comparable qualification where required", "German or English language ability appropriate to the job", "Genuine employer offer", "Professional registration for regulated occupations"],
    documentFocus: ["Passport", "CV in suitable format", "Qualification certificates and transcripts", "Recognition decision where applicable", "Employment contract", "Language and professional-registration evidence"],
    languageLicensing: "German is important for many workplaces and can be mandatory in healthcare, care and customer-facing roles. Regulated professions require formal recognition or licensing.",
    employmentNotes: "Employment contracts should clearly state gross salary, hours, probation, leave and collective-agreement conditions where relevant. Taxes and social insurance are deducted from gross pay.",
    arrivalPreparation: "Prepare for address registration, residence-permit formalities, health insurance, tax identification and employer onboarding after arrival."
  }),
  guide({
    slug: "france",
    seoTitle: "France Jobs & Recruitment Guide 2026 | Work Permit & Talent Residence",
    seoDescription: "France recruitment guide covering jobs, employer work authorization, talent and skilled routes, French language, documents and candidate preparation.",
    overview: "France employs international workers in hospitality, healthcare, logistics, construction, agriculture, engineering, technology and specialist professions. For many non-EU workers, the employer and immigration process are closely linked.",
    recruitmentFocus: "The employer may need to obtain work authorization before the candidate applies for the appropriate long-stay visa or residence category. Highly skilled and talent routes can follow different procedures.",
    workRoute: "A standard process can involve employer work authorization followed by a long-stay visa and residence validation. The exact route depends on occupation, salary, qualification, nationality and duration of employment.",
    jobKeys: ["hotel", "housekeeper", "cook", "warehouse", "farm-worker", "construction", "electrician", "mechanic", "nurse", "software", "engineer"],
    candidateRequirements: ["Valid passport", "Employer offer", "Relevant experience and qualifications", "French ability where necessary", "Professional recognition for regulated work"],
    documentFocus: ["Passport", "CV", "Employment contract", "Work authorization where applicable", "Qualifications", "Civil and professional documents requested for the visa"],
    languageLicensing: "French is important for most customer-facing and operational roles. Healthcare and regulated professions require recognition and registration.",
    employmentNotes: "Contracts should be reviewed for gross salary, working time, leave, probation and collective-agreement terms. Social charges are normally deducted from gross salary.",
    arrivalPreparation: "Follow long-stay visa validation or residence-permit instructions and complete health-insurance, banking and employer onboarding steps."
  }),
  guide({
    slug: "italy",
    seoTitle: "Italy Jobs & Recruitment Guide 2026 | Work Visa & Decreto Flussi",
    seoDescription: "Explore Italy recruitment, seasonal and employed work routes, jobs, employer authorization, documents, Italian language and Red Stone support.",
    overview: "Italy recruits foreign workers in agriculture, tourism, hospitality, domestic support, construction, manufacturing and selected skilled occupations. Many non-EU work entries are connected to annual quota programmes and employer authorization.",
    recruitmentFocus: "Seasonal and non-seasonal recruitment may depend on the annual Decreto Flussi framework, while some highly skilled or special categories operate outside the normal quotas.",
    workRoute: "For quota-based employment, the employer generally seeks the required work authorization before the worker applies for a national visa. After arrival, residence-permit procedures must be completed within the required timeframe.",
    jobKeys: ["farm-worker", "horticulture", "housekeeper", "caregiver", "hotel", "waiter", "cook", "construction", "factory", "warehouse", "mechanic"],
    candidateRequirements: ["Valid passport", "Employer authorization for the applicable route", "Job-relevant experience", "Italian ability for many roles", "Required qualifications for skilled occupations"],
    documentFocus: ["Passport", "Employment offer", "Work authorization / nulla osta where applicable", "Qualifications", "Visa application records", "Residence-permit documentation"],
    languageLicensing: "Italian is important for most daily work and customer-facing positions. Regulated professions require recognition of foreign qualifications.",
    employmentNotes: "Seasonal employment, accommodation and transport arrangements should be reviewed carefully in writing. Pay is influenced by sector agreements and contract classification.",
    arrivalPreparation: "Complete the residence-permit process promptly after arrival and keep copies of the employment authorization and signed contract."
  }),
  guide({
    slug: "netherlands",
    seoTitle: "Netherlands Jobs & Recruitment Guide 2026 | Work Permit & Highly Skilled Migrant",
    seoDescription: "Netherlands recruitment guide for jobs, employer work permits, highly skilled migrant routes, documents, English/Dutch and Red Stone candidate support.",
    overview: "The Netherlands recruits international workers in logistics, warehousing, agriculture, food production, engineering, technology, hospitality and specialist professional roles. Work authorization differs between highly skilled, intra-company and standard labour routes.",
    recruitmentFocus: "Recognized sponsors play an important role in highly skilled migration, while other jobs may require combined residence and work authorization or labour-market testing.",
    workRoute: "The employer may apply for the relevant work and residence authorization, depending on the route. The worker then completes identity, entry visa or residence-card steps as instructed by Dutch immigration authorities.",
    jobKeys: ["warehouse", "logistics", "horticulture", "food-production", "factory", "hotel", "cook", "technician", "it-support", "software", "engineer"],
    candidateRequirements: ["Valid passport", "Genuine employer offer", "Relevant experience", "Salary or qualification criteria for specialist routes", "Work and residence eligibility"],
    documentFocus: ["Passport", "CV", "Employment contract", "Qualification records", "Employer sponsorship / permit documents", "Residence application records"],
    languageLicensing: "English is common in international workplaces, but Dutch improves access to operational and customer-facing roles. Regulated professions require local recognition.",
    employmentNotes: "Review gross salary, holiday allowance, working hours, housing deductions and agency conditions where relevant. Do not assume accommodation is free unless stated.",
    arrivalPreparation: "Prepare for municipal registration, residence-card collection, health insurance, tax / citizen-service number registration and employer onboarding."
  }),
  guide({
    slug: "switzerland",
    seoTitle: "Switzerland Jobs & Recruitment Guide 2026 | Work Permit Careers",
    seoDescription: "Explore Switzerland recruitment, skilled jobs, employer work permit process, qualification recognition, language requirements and Red Stone guidance.",
    overview: "Switzerland offers high-skill opportunities in healthcare, engineering, IT, hospitality, finance, life sciences and technical fields, but work permits for non-EU/EFTA nationals are selective and generally focused on highly qualified workers.",
    recruitmentFocus: "Employers seeking non-EU/EFTA workers normally must demonstrate that the recruitment meets Swiss labour-market and qualification requirements. Cantonal and federal approvals can both be involved.",
    workRoute: "The employer typically initiates the work-permit application with the relevant canton. After approvals, the worker completes any required visa and registration steps. Permit quotas and qualification criteria can apply.",
    jobKeys: ["nurse", "hotel", "chef", "technician", "it-support", "software", "engineer", "mechanic"],
    candidateRequirements: ["Valid passport", "Strong professional qualifications", "Relevant experience", "Employer sponsorship", "Language and professional recognition where required"],
    documentFocus: ["Passport", "Detailed CV", "Qualification certificates", "Employment contract", "Work-permit approval documents", "Professional registration evidence where applicable"],
    languageLicensing: "German, French or Italian may be required depending on the canton and role. English is common in some international companies. Healthcare and regulated professions require recognition.",
    employmentNotes: "Swiss salaries are high relative to many markets, but living costs are also high. Candidates should assess gross salary, canton, housing, insurance and tax obligations together.",
    arrivalPreparation: "Register locally within the required period, arrange mandatory health insurance and complete residence-permit and employer onboarding formalities."
  }),
  guide({
    slug: "sweden",
    seoTitle: "Sweden Jobs & Recruitment Guide 2026 | Work Permit Careers",
    seoDescription: "Sweden recruitment guide covering jobs, employer work permit process, salary and employment conditions, documents, language and Red Stone support.",
    overview: "Sweden recruits international workers in technology, engineering, healthcare, industry, hospitality, logistics and selected skilled occupations. Employer terms must meet Swedish work-permit and employment standards.",
    recruitmentFocus: "A genuine employer offer and compliant employment conditions are central to standard work permits. Some highly qualified workers may use separate job-seeker or research-related routes.",
    workRoute: "The employer begins the employment offer process and the candidate completes the work-permit application with required passport, qualification and employment evidence. Trade-union input can form part of the employer process.",
    jobKeys: ["nurse", "warehouse", "factory", "hotel", "cook", "construction", "technician", "it-support", "software", "engineer"],
    candidateRequirements: ["Valid passport", "Compliant employment offer", "Relevant qualifications and experience", "Health or professional registration where applicable", "Ability to meet current work-permit conditions"],
    documentFocus: ["Passport", "CV", "Employment offer", "Qualifications", "Professional registration where required", "Work-permit application records"],
    languageLicensing: "English is common in technology and international companies, while Swedish is important in healthcare, public-facing and many operational roles. Regulated occupations require Swedish recognition or authorization.",
    employmentNotes: "Candidates should review salary, insurance, pension and collective-agreement conditions. Work-permit salary requirements can change and should be verified officially.",
    arrivalPreparation: "Follow residence-card, population-registration, tax and banking instructions after arrival and maintain the employment conditions attached to the permit."
  }),
  guide({
    slug: "norway",
    seoTitle: "Norway Jobs & Recruitment Guide 2026 | Skilled Worker Residence",
    seoDescription: "Explore Norway jobs, skilled worker residence process, qualifications, employer requirements, language, documents and Red Stone recruitment guidance.",
    overview: "Norway recruits skilled workers in healthcare, engineering, construction, maritime, energy, technology, hospitality and technical trades. Standard skilled-worker routes normally require relevant qualifications and a concrete job offer.",
    recruitmentFocus: "The job should normally require skilled qualifications and the applicant must have education, vocational training or special qualifications relevant to the role. Salary and working conditions must meet Norwegian standards.",
    workRoute: "The worker applies for a skilled-worker residence permit based on the employment offer, or the employer may assist with parts of the process. Professional authorization is separate for regulated occupations.",
    jobKeys: ["nurse", "construction", "electrician", "plumber", "welder", "mechanic", "hotel", "cook", "technician", "software", "engineer"],
    candidateRequirements: ["Valid passport", "Relevant skilled qualification", "Concrete job offer", "Norwegian-standard employment conditions", "Professional authorization where applicable"],
    documentFocus: ["Passport", "CV", "Employment offer", "Education / vocational certificates", "Employment references", "Professional authorization records"],
    languageLicensing: "Norwegian is important in healthcare and many public-facing jobs, while English can be sufficient in some technical and international workplaces. Regulated roles require authorization.",
    employmentNotes: "Norway has high wages and high living costs. Review gross salary, tax, housing and any rotation or travel arrangements before accepting employment.",
    arrivalPreparation: "Complete police / residence registration, tax-card, identity-number and banking steps as instructed after arrival."
  }),
  guide({
    slug: "denmark",
    seoTitle: "Denmark Jobs & Recruitment Guide 2026 | Work Residence Careers",
    seoDescription: "Denmark recruitment guide covering skilled jobs, Positive List and pay-limit routes, employer requirements, documents, language and Red Stone support.",
    overview: "Denmark recruits international professionals in engineering, healthcare, technology, life sciences, manufacturing, construction and selected hospitality roles. Several work-residence schemes are tied to occupation shortages or salary criteria.",
    recruitmentFocus: "Applicants should identify the immigration scheme that fits the job, such as shortage-occupation or pay-based routes. The offer must meet Danish employment standards.",
    workRoute: "The employer and worker prepare the required employment information and the candidate applies for work and residence under the relevant scheme. Biometrics and professional authorization may be separate requirements.",
    jobKeys: ["nurse", "construction", "electrician", "welder", "technician", "warehouse", "hotel", "cook", "software", "engineer"],
    candidateRequirements: ["Valid passport", "Eligible job offer", "Relevant qualification", "Salary and employment terms meeting scheme rules", "Professional authorization where required"],
    documentFocus: ["Passport", "Employment contract", "CV", "Qualifications", "Biometric application records", "Professional registration documents"],
    languageLicensing: "English is common in international employers, but Danish is important in healthcare and public-facing work. Healthcare professionals require Danish authorization.",
    employmentNotes: "Assess salary together with taxes, pension and living costs. Collective agreements can influence working conditions even where no statutory national minimum wage applies.",
    arrivalPreparation: "Complete residence registration, CPR number, tax, health-card and banking steps after arrival."
  }),
  guide({
    slug: "finland",
    seoTitle: "Finland Jobs & Recruitment Guide 2026 | Work Residence Permit",
    seoDescription: "Explore Finland recruitment, jobs, employed-person residence permits, specialist routes, language, documents and Red Stone application guidance.",
    overview: "Finland recruits workers in healthcare, technology, manufacturing, logistics, construction, hospitality, cleaning and seasonal agriculture. Work-residence routes differ for employed persons, specialists, seasonal workers and other categories.",
    recruitmentFocus: "The employer's job offer, occupation and terms determine the most appropriate residence-permit category. Labour-market assessment may apply to some employed-person permits.",
    workRoute: "The candidate applies for the relevant work-based residence permit and the employer provides required employment information. Identity verification, health, professional recognition or seasonal-work rules can apply.",
    jobKeys: ["cleaner", "warehouse", "factory", "food-production", "farm-worker", "construction", "nurse", "technician", "it-support", "software", "engineer"],
    candidateRequirements: ["Valid passport", "Genuine employment offer", "Relevant experience or qualification", "Ability to meet permit conditions", "Professional authorization for regulated jobs"],
    documentFocus: ["Passport", "Employment contract", "CV", "Qualification certificates", "Employer terms-of-employment information", "Residence-permit records"],
    languageLicensing: "English is used in many technology and international workplaces, while Finnish or Swedish is important for healthcare and customer-facing roles. Regulated healthcare requires authorization.",
    employmentNotes: "Sector collective agreements often influence pay and working conditions. Candidates should review gross salary, shift allowances and housing costs.",
    arrivalPreparation: "Complete residence-card, population-data, tax, banking and employer onboarding steps after arrival."
  }),
  guide({
    slug: "poland",
    seoTitle: "Poland Jobs & Recruitment Guide 2026 | Work Permit & Visa",
    seoDescription: "Detailed Poland recruitment guide for factory, warehouse, construction and skilled jobs, employer work permits, visas, documents and candidate preparation.",
    overview: "Poland recruits international workers in manufacturing, warehouses, food production, logistics, construction, hospitality, agriculture and technical trades. Employer work authorization is commonly required for non-EU workers.",
    recruitmentFocus: "Candidates should verify the employer, workplace location, job duties, hourly or monthly pay, accommodation deductions and the exact work authorization before travel.",
    workRoute: "The employer normally obtains the relevant work permit or declaration where legally available. The worker then applies for the appropriate visa or residence status and must work under the approved conditions.",
    jobKeys: ["factory", "food-production", "warehouse", "logistics", "construction", "welder", "mechanic", "hotel", "cook", "farm-worker"],
    candidateRequirements: ["Valid passport", "Employer work authorization", "Job-relevant experience where required", "Medical or safety fitness for industrial work", "Compliance with visa / residence conditions"],
    documentFocus: ["Passport", "Work permit / declaration", "Employment contract", "CV", "Qualifications for skilled work", "Visa or residence records"],
    languageLicensing: "Polish improves workplace communication and is often important outside international teams. Some employers use English for technical roles. Regulated professions require recognition.",
    employmentNotes: "Check whether salary is gross or net and review accommodation, transport, agency deductions, overtime and shift premiums in writing.",
    arrivalPreparation: "Keep the work authorization and contract available, complete residence or registration obligations and work only for the employer and conditions permitted by the authorization."
  }),
  guide({
    slug: "austria",
    seoTitle: "Austria Jobs & Recruitment Guide 2026 | Red-White-Red Card",
    seoDescription: "Austria recruitment guide covering skilled jobs, Red-White-Red Card, EU Blue Card, qualifications, German language and Red Stone candidate support.",
    overview: "Austria recruits international skilled workers in healthcare, engineering, tourism, hospitality, construction, manufacturing, IT and shortage occupations. The Red-White-Red Card and EU Blue Card are important work-residence pathways.",
    recruitmentFocus: "Eligibility can depend on occupation shortage, qualifications, work experience, salary and points criteria. German-language ability improves access to many jobs and can contribute to some routes.",
    workRoute: "The candidate and employer submit the required work-residence application under the appropriate category. Qualification recognition or professional authorization may be needed before regulated work begins.",
    jobKeys: ["nurse", "hotel", "cook", "construction", "electrician", "welder", "mechanic", "technician", "it-support", "software", "engineer"],
    candidateRequirements: ["Valid passport", "Eligible employer offer", "Relevant qualifications", "German or English ability appropriate to the role", "Points / salary / professional requirements of the chosen route"],
    documentFocus: ["Passport", "CV", "Employment contract", "Qualification and experience records", "Language evidence where relevant", "Professional recognition documents"],
    languageLicensing: "German is important in most operational and healthcare roles. English can be common in technology and multinational employers. Regulated professions require Austrian recognition.",
    employmentNotes: "Collective agreements strongly influence salary and employment conditions. Candidates should check gross monthly salary and whether additional annual payments apply.",
    arrivalPreparation: "Complete residence registration, health insurance, tax and residence-card formalities after arrival."
  }),
  guide({
    slug: "ireland",
    seoTitle: "Ireland Jobs & Recruitment Guide 2026 | Employment Permit Careers",
    seoDescription: "Explore Ireland jobs, Critical Skills and General Employment Permits, healthcare, hospitality, construction and Red Stone recruitment guidance.",
    overview: "Ireland recruits international workers in healthcare, technology, engineering, construction, hospitality, logistics and other shortage occupations. Non-EEA employment commonly requires an employment permit unless an exemption applies.",
    recruitmentFocus: "The occupation and salary determine whether a Critical Skills, General or another permit category may apply. Some occupations are excluded from employment permits, so job eligibility must be checked before recruitment.",
    workRoute: "After a genuine job offer, the employer or worker applies for the appropriate employment permit. Visa-required nationals then complete the entry-visa process, followed by immigration registration after arrival.",
    jobKeys: ["nurse", "healthcare-assistant", "hotel", "cook", "construction", "electrician", "technician", "it-support", "software", "engineer"],
    candidateRequirements: ["Valid passport", "Eligible job offer", "Required salary and occupation criteria", "Relevant qualifications", "Professional registration for regulated work"],
    documentFocus: ["Passport", "Employment contract", "Employment permit records", "Qualifications", "Professional registration", "Visa and immigration-registration records"],
    languageLicensing: "English is the principal workplace language. Healthcare professionals must meet Irish professional-registration and language standards where applicable.",
    employmentNotes: "Housing costs can be significant, especially in major cities. Candidates should compare salary with location, accommodation and transport before accepting an offer.",
    arrivalPreparation: "Complete immigration registration, tax / PPS number, banking and employer onboarding steps after arrival."
  }),
  guide({
    slug: "luxembourg",
    seoTitle: "Luxembourg Jobs & Recruitment Guide 2026 | Work Residence Careers",
    seoDescription: "Luxembourg recruitment guide covering international jobs, salaried-worker permits, EU Blue Card, multilingual requirements, documents and Red Stone support.",
    overview: "Luxembourg has a multilingual labour market with opportunities in finance, hospitality, logistics, construction, IT, engineering and specialist professional services. Non-EU recruitment generally requires work and residence authorization.",
    recruitmentFocus: "For standard salaried employment, employers may need to complete labour-market steps before a third-country national applies for authorization to stay. Highly qualified workers can have a separate EU Blue Card route.",
    workRoute: "A typical third-country salaried-worker process involves employer labour-market formalities, authorization to stay, entry visa where required and residence-permit registration after arrival.",
    jobKeys: ["hotel", "housekeeper", "cook", "warehouse", "logistics", "construction", "technician", "it-support", "software", "engineer"],
    candidateRequirements: ["Valid passport", "Eligible job offer", "Relevant qualifications or experience", "Language ability appropriate to the workplace", "Work and residence authorization"],
    documentFocus: ["Passport", "CV", "Employment contract", "Employer labour-market evidence where required", "Qualifications", "Authorization / residence records"],
    languageLicensing: "French, German and Luxembourgish are widely used, while English is common in finance, IT and multinational companies. Language requirements depend strongly on the job.",
    employmentNotes: "Luxembourg salaries can be attractive but housing costs are high. Candidates should assess commuting, accommodation and deductions alongside gross salary.",
    arrivalPreparation: "Complete local declaration of arrival, medical / residence formalities where required, social-security registration, tax and banking steps."
  }),
];

export function getCountryRecruitmentGuide(slug: string) {
  return COUNTRY_RECRUITMENT_GUIDES.find((item) => item.slug === slug);
}
