export type SponsorshipJob = {
  country: string;
  countrySlug: string;
  region: string;
  role: string;
  roleSlug: string;
  salary: string;
  salaryNote: string;
  summary: string;
  duties: string[];
  requirements: string[];
};

export const SPONSORSHIP_INTAKE_DEADLINE = "2026-10-06T23:59:59+03:00";

export const SPONSORSHIP_BENEFITS = [
  "Visa or work-authorization processing costs where covered by the sponsoring employer",
  "Economy air ticket for deployment where included in the written offer",
  "Employer-provided accommodation or housing support",
  "Food, meals or a food allowance where included in the employment package",
  "Basic employer-arranged insurance where applicable",
  "Employer onboarding and arrival coordination",
] as const;

export const SPONSORSHIP_MEDICALS = [
  {
    label: "Gulf medical",
    amount: "KES 12,500",
    note: "For Gulf placements where this medical route is the applicable requirement.",
  },
  {
    label: "Non-Gulf medical",
    amount: "KES 31,060",
    note: "For qualifying non-Gulf recruitment cases where this medical route applies.",
  },
  {
    label: "IOM medical route",
    amount: "KES 41,000",
    note: "Where IOM or the relevant approved medical route is appropriate or required for the case.",
  },
] as const;

export const SPONSORSHIP_APPLICATION_FEE = {
  amount: "KES 2,000",
  label: "CV & Document Verification Fee",
  note: "Charged at the application payment stage for CV review, document verification, application record preparation and submission processing. It is not payment for employment, sponsorship, a visa, or guaranteed placement.",
} as const;

export const SPONSORSHIP_JOBS: SponsorshipJob[] = [
  {
    country: "United States",
    countrySlug: "usa",
    region: "North America",
    role: "Nanny / Childcare Worker",
    roleSlug: "nanny-childcare-worker",
    salary: "USD 15-22 per hour",
    salaryNote: "Indicative range aligned with mainstream childcare pay. Final pay depends on state, employer, hours and written contract.",
    summary: "Provide safe, dependable childcare in a private household or approved care setting, supporting daily routines, meals, play, supervision and age-appropriate activities.",
    duties: ["Supervise children safely", "Prepare simple meals and snacks", "Support routines, hygiene and activities", "Keep child areas tidy", "Communicate clearly with parents or supervisors"],
    requirements: ["Genuine childcare or household-care experience preferred", "Good communication and reliability", "Police clearance where required", "Ability to follow household and safeguarding rules", "Eligibility for the employer's lawful U.S. sponsorship pathway"],
  },
  {
    country: "United States",
    countrySlug: "usa",
    region: "North America",
    role: "Security Guard",
    roleSlug: "security-guard",
    salary: "USD 16-24 per hour",
    salaryNote: "Indicative employer range; licensing and pay differ by state and assignment.",
    summary: "Protect people, premises and property through access control, patrols, observation, incident reporting and professional response to workplace security procedures.",
    duties: ["Monitor entrances and restricted areas", "Conduct routine patrols", "Record incidents accurately", "Support emergency procedures", "Provide professional visitor assistance"],
    requirements: ["Security experience is an advantage", "Clean conduct record where required", "Ability to stand or patrol for long periods", "State licence or training where required", "Eligibility for the employer's lawful U.S. sponsorship pathway"],
  },
  {
    country: "United States",
    countrySlug: "usa",
    region: "North America",
    role: "Housekeeper",
    roleSlug: "housekeeper",
    salary: "USD 15-21 per hour",
    salaryNote: "Indicative range for ordinary housekeeping work; final pay varies by location and employer.",
    summary: "Maintain clean, safe and organized living or hospitality spaces through routine cleaning, bed making, laundry support and careful handling of household or guest-room items.",
    duties: ["Clean rooms and common areas", "Make beds and change linen", "Handle laundry where assigned", "Restock basic supplies", "Follow hygiene and safety procedures"],
    requirements: ["Housekeeping or cleaning experience preferred", "Attention to detail", "Physical ability for routine cleaning tasks", "Reliable work habits", "Eligibility for the employer's lawful U.S. sponsorship pathway"],
  },
  {
    country: "United States",
    countrySlug: "usa",
    region: "North America",
    role: "Caregiver / Personal Care Aide",
    roleSlug: "caregiver-personal-care-aide",
    salary: "USD 15-21 per hour",
    salaryNote: "Indicative range close to mainstream personal-care earnings; certification requirements vary by employer and state.",
    summary: "Support older adults or people who need daily-living assistance with respectful personal care, mobility, meals, companionship and routine household support within the worker's authorized scope.",
    duties: ["Assist with daily living activities", "Support mobility and safe movement", "Prepare simple meals", "Provide companionship", "Report concerns to the appropriate supervisor"],
    requirements: ["Caregiving experience preferred", "Compassion and patience", "Relevant training where required", "Background checks where required", "Eligibility for the employer's lawful U.S. sponsorship pathway"],
  },
  {
    country: "Canada",
    countrySlug: "canada",
    region: "North America",
    role: "Housekeeper",
    roleSlug: "housekeeper",
    salary: "CAD 16-25 per hour",
    salaryNote: "Indicative range consistent with Canadian light-duty cleaner wage data; actual pay depends on province and employer.",
    summary: "Clean hotel rooms, residences, offices or institutional spaces, maintain hygiene standards, change linen and keep assigned areas orderly and ready for use.",
    duties: ["Clean guest or residential areas", "Change bedding and linen", "Sanitize bathrooms and surfaces", "Restock supplies", "Report maintenance or safety issues"],
    requirements: ["Cleaning experience helpful but not always required", "Good work ethic", "Ability to perform physical cleaning tasks", "Basic communication skills", "Employer selection and Canadian work authorization eligibility"],
  },
  {
    country: "Canada",
    countrySlug: "canada",
    region: "North America",
    role: "Commercial Cleaner",
    roleSlug: "commercial-cleaner",
    salary: "CAD 16-25 per hour",
    salaryNote: "Indicative range; provincial minimum wages and employer contracts apply.",
    summary: "Provide routine commercial cleaning for offices, hospitality facilities, public spaces or institutions using safe cleaning methods and assigned equipment.",
    duties: ["Sweep, mop and vacuum floors", "Clean washrooms and common areas", "Dispose of waste safely", "Use cleaning products correctly", "Follow site safety procedures"],
    requirements: ["Reliability and punctuality", "Ability to work independently", "Physical fitness for routine cleaning", "Experience is an advantage", "Employer selection and Canadian work authorization eligibility"],
  },
  {
    country: "Canada",
    countrySlug: "canada",
    region: "North America",
    role: "Warehouse Worker / Material Handler",
    roleSlug: "warehouse-material-handler",
    salary: "CAD 17-30 per hour",
    salaryNote: "Indicative range consistent with Canadian material-handler wage data; location and shift premiums vary.",
    summary: "Receive, move, sort, pack and prepare goods in a warehouse or distribution environment while following inventory, lifting and workplace-safety procedures.",
    duties: ["Load and unload goods", "Pick and pack orders", "Label and sort inventory", "Maintain clean work areas", "Follow warehouse safety rules"],
    requirements: ["Warehouse experience helpful", "Ability to lift within safe workplace limits", "Attention to labels and instructions", "Forklift certification only where required", "Employer selection and Canadian work authorization eligibility"],
  },
  {
    country: "Canada",
    countrySlug: "canada",
    region: "North America",
    role: "General Farm Worker",
    roleSlug: "general-farm-worker",
    salary: "CAD 16-25 per hour",
    salaryNote: "Indicative range consistent with Canadian general farm-worker wage data; seasonal and regional differences apply.",
    summary: "Support crop, livestock or mixed-farm operations with routine field, feeding, harvesting, cleaning and basic farm-maintenance duties under employer supervision.",
    duties: ["Assist with planting or harvesting", "Feed or care for livestock where assigned", "Clean work areas and equipment", "Sort or pack produce", "Follow farm health and safety rules"],
    requirements: ["Farm experience is an advantage", "Ability to work outdoors", "Physical readiness for manual work", "Reliability during seasonal schedules", "Employer selection and Canadian work authorization eligibility"],
  },
  {
    country: "Canada",
    countrySlug: "canada",
    region: "North America",
    role: "Transport Truck Driver",
    roleSlug: "transport-truck-driver",
    salary: "CAD 22-35 per hour",
    salaryNote: "Indicative mainstream range; Canadian Job Bank reports a national median around CAD 26 per hour for transport truck drivers.",
    summary: "Operate commercial trucks safely on assigned routes, complete vehicle checks, manage delivery documentation and comply with road, hours-of-service and employer transport procedures.",
    duties: ["Complete pre-trip inspections", "Transport goods safely", "Maintain delivery records", "Follow route and rest requirements", "Report vehicle or load issues"],
    requirements: ["Relevant commercial driving experience", "Required class of driving licence", "Clean driving record where required", "Ability to meet medical and transport standards", "Employer selection and Canadian work authorization eligibility"],
  },
  {
    country: "New Zealand",
    countrySlug: "new-zealand",
    region: "Oceania",
    role: "Cleaner",
    roleSlug: "cleaner",
    salary: "NZD 24-31 per hour",
    salaryNote: "Indicative ordinary market range. Actual wage must meet New Zealand employment law and the written offer.",
    summary: "Maintain clean and hygienic workplaces, accommodation, hospitality or institutional facilities using approved products, equipment and site procedures.",
    duties: ["Clean floors and surfaces", "Sanitize washrooms", "Empty waste safely", "Restock cleaning supplies", "Follow site health and safety instructions"],
    requirements: ["Cleaning experience helpful", "Reliable attendance", "Ability to work rostered shifts", "Basic workplace communication", "Employer selection and New Zealand work-visa eligibility"],
  },
  {
    country: "New Zealand",
    countrySlug: "new-zealand",
    region: "Oceania",
    role: "Aged Care Support Worker",
    roleSlug: "aged-care-support-worker",
    salary: "NZD 25-32 per hour",
    salaryNote: "Indicative range; qualifications, employer agreements and care setting affect pay.",
    summary: "Provide respectful day-to-day support to older people in residential or community settings, assisting with routines, mobility, meals, companionship and approved care tasks.",
    duties: ["Support daily living routines", "Assist safe mobility", "Provide companionship", "Support meals and hydration", "Record and report observations"],
    requirements: ["Care experience preferred", "Compassion and patience", "Training or certification where required", "Police vetting where required", "Employer selection and New Zealand work-visa eligibility"],
  },
  {
    country: "New Zealand",
    countrySlug: "new-zealand",
    region: "Oceania",
    role: "Warehouse Storeperson",
    roleSlug: "warehouse-storeperson",
    salary: "NZD 24-32 per hour",
    salaryNote: "Indicative range for routine warehousing; shift, experience and licence premiums may apply.",
    summary: "Receive, store, pick, pack and dispatch goods while keeping inventory accurate and maintaining safe warehouse handling practices.",
    duties: ["Receive and check deliveries", "Pick and pack orders", "Move stock safely", "Update labels or records", "Maintain safe aisles and work areas"],
    requirements: ["Warehouse experience helpful", "Good attention to detail", "Safe manual-handling ability", "Forklift endorsement only where required", "Employer selection and New Zealand work-visa eligibility"],
  },
  {
    country: "New Zealand",
    countrySlug: "new-zealand",
    region: "Oceania",
    role: "Farm Assistant",
    roleSlug: "farm-assistant",
    salary: "NZD 24-31 per hour",
    salaryNote: "Indicative range; farm type, roster, accommodation arrangements and experience affect the final offer.",
    summary: "Assist with daily farm operations such as livestock care, feeding, cleaning, fencing, harvesting or general maintenance depending on the employer's operation.",
    duties: ["Assist livestock or crop operations", "Clean facilities and equipment", "Support feeding or harvesting", "Carry out basic maintenance", "Follow farm safety and biosecurity rules"],
    requirements: ["Farm experience advantageous", "Comfort working outdoors", "Ability to follow early or rotating schedules", "Practical attitude", "Employer selection and New Zealand work-visa eligibility"],
  },
  {
    country: "New Zealand",
    countrySlug: "new-zealand",
    region: "Oceania",
    role: "Truck Driver",
    roleSlug: "truck-driver",
    salary: "NZD 28-38 per hour",
    salaryNote: "Indicative range; licence class, route type, experience and employer determine final pay.",
    summary: "Drive commercial vehicles safely, complete vehicle inspections, transport goods and maintain route, delivery and compliance records.",
    duties: ["Inspect vehicle before travel", "Transport goods safely", "Complete delivery paperwork", "Secure loads where required", "Follow driving-hour and road rules"],
    requirements: ["Commercial driving experience", "Correct New Zealand-recognized licence or conversion eligibility", "Safe driving record", "Ability to meet transport medical standards", "Employer selection and work-visa eligibility"],
  },
  {
    country: "Australia",
    countrySlug: "australia",
    region: "Oceania",
    role: "Commercial / Domestic Cleaner",
    roleSlug: "cleaner",
    salary: "AUD 27-35 per hour",
    salaryNote: "Indicative range around mainstream cleaner earnings; awards, penalty rates and location affect actual pay.",
    summary: "Clean residential, commercial, hospitality or institutional areas to required hygiene and presentation standards using approved equipment and safe work practices.",
    duties: ["Vacuum, mop and clean surfaces", "Sanitize washrooms", "Dispose of waste", "Restock consumables", "Follow chemical and workplace-safety procedures"],
    requirements: ["Cleaning experience helpful", "Reliable attendance", "Physical ability for routine cleaning", "Ability to follow workplace instructions", "Employer selection and Australian work-right eligibility"],
  },
  {
    country: "Australia",
    countrySlug: "australia",
    region: "Oceania",
    role: "Aged / Disability Support Worker",
    roleSlug: "aged-disability-support-worker",
    salary: "AUD 32-46 per hour",
    salaryNote: "Indicative range; Australian official data show relatively strong hourly earnings in aged and disability care, while awards and qualifications affect pay.",
    summary: "Support older people or people with disabilities with daily living, mobility, household routines, community participation and approved personal-care tasks.",
    duties: ["Assist daily living activities", "Support mobility", "Prepare meals", "Provide companionship and community support", "Complete required care records"],
    requirements: ["Care experience or relevant training preferred", "Background checks where required", "First aid or care credentials where required", "Respectful communication", "Employer selection and Australian work-right eligibility"],
  },
  {
    country: "Australia",
    countrySlug: "australia",
    region: "Oceania",
    role: "Warehouse Storeperson",
    roleSlug: "warehouse-storeperson",
    salary: "AUD 30-38 per hour",
    salaryNote: "Indicative range; Australian Jobs and Skills data report median hourly earnings around AUD 34 for storepersons.",
    summary: "Receive, store, pick, pack and dispatch stock while maintaining accurate inventory flow and safe manual-handling procedures.",
    duties: ["Receive deliveries", "Pick and pack stock", "Move and label goods", "Prepare dispatches", "Maintain warehouse safety"],
    requirements: ["Warehouse experience helpful", "Safe manual-handling ability", "Attention to stock records", "Forklift licence only where required", "Employer selection and Australian work-right eligibility"],
  },
  {
    country: "Australia",
    countrySlug: "australia",
    region: "Oceania",
    role: "Farm Hand",
    roleSlug: "farm-hand",
    salary: "AUD 27-35 per hour",
    salaryNote: "Indicative range; award coverage, farm type, season, location and experience affect pay.",
    summary: "Assist with crop, livestock or mixed-farm duties including feeding, harvesting, cleaning, basic maintenance and general farm operations.",
    duties: ["Assist planting or harvest work", "Support livestock routines", "Clean sheds or equipment", "Carry out basic maintenance", "Follow farm safety procedures"],
    requirements: ["Farm experience advantageous", "Physical readiness for outdoor work", "Ability to work rostered hours", "Reliable attendance", "Employer selection and Australian work-right eligibility"],
  },
  {
    country: "Australia",
    countrySlug: "australia",
    region: "Oceania",
    role: "Delivery / Truck Driver",
    roleSlug: "delivery-truck-driver",
    salary: "AUD 30-42 per hour",
    salaryNote: "Indicative range; vehicle class, award, route, overtime and experience affect final pay.",
    summary: "Operate delivery or freight vehicles safely, complete route documentation, inspect vehicles and ensure goods reach customers or facilities in good order.",
    duties: ["Inspect vehicle", "Load or secure goods where assigned", "Complete deliveries", "Maintain route records", "Follow road and fatigue-management rules"],
    requirements: ["Relevant driving experience", "Correct licence class", "Safe driving history", "Ability to meet transport requirements", "Employer selection and Australian work-right eligibility"],
  },
  {
    country: "Gulf Countries",
    countrySlug: "gulf",
    region: "Gulf / Middle East",
    role: "Security Guard",
    roleSlug: "security-guard",
    salary: "UAE AED 1,800-3,000 / Qatar QAR 1,800-3,000 / Saudi SAR 2,000-3,500 monthly",
    salaryNote: "Indicative employer ranges for ordinary security assignments. Final contract, legal requirements and benefits vary by Gulf country.",
    summary: "Provide access control, patrol, observation and incident reporting for commercial, residential, hospitality or industrial premises.",
    duties: ["Control access points", "Conduct patrols", "Monitor assigned areas", "Write incident reports", "Follow emergency procedures"],
    requirements: ["Security experience preferred", "Good conduct record", "Physical fitness for patrol duties", "Local security training or licence where required", "Employer selection and destination work-authorization eligibility"],
  },
  {
    country: "Gulf Countries",
    countrySlug: "gulf",
    region: "Gulf / Middle East",
    role: "Housekeeper",
    roleSlug: "housekeeper",
    salary: "UAE AED 1,500-2,500 / Qatar QAR 1,500-2,500 / Saudi SAR 1,500-2,500 monthly",
    salaryNote: "Indicative ordinary employer range; accommodation, meals and other benefits can materially affect the package.",
    summary: "Maintain guest rooms, residences or staff accommodation to the required cleanliness, hygiene and presentation standards.",
    duties: ["Clean rooms and common areas", "Change linen", "Sanitize bathrooms", "Restock supplies", "Report maintenance concerns"],
    requirements: ["Housekeeping experience helpful", "Attention to detail", "Ability to work rostered shifts", "Reliable conduct", "Employer selection and destination work-authorization eligibility"],
  },
  {
    country: "Gulf Countries",
    countrySlug: "gulf",
    region: "Gulf / Middle East",
    role: "Warehouse Assistant",
    roleSlug: "warehouse-assistant",
    salary: "UAE AED 1,800-3,000 / Qatar QAR 1,800-3,000 / Saudi SAR 2,000-3,500 monthly",
    salaryNote: "Indicative ordinary range; overtime, shift allowance and employer benefits vary.",
    summary: "Support receiving, storage, picking, packing and dispatch operations while following warehouse safety and inventory procedures.",
    duties: ["Load and unload stock", "Pick and pack orders", "Label goods", "Maintain organized storage", "Follow warehouse safety rules"],
    requirements: ["Warehouse experience is an advantage", "Safe manual-handling ability", "Basic numeracy and attention to labels", "Forklift skill where required", "Employer selection and destination work-authorization eligibility"],
  },
  {
    country: "Gulf Countries",
    countrySlug: "gulf",
    region: "Gulf / Middle East",
    role: "Hospitality Helper / Waiter",
    roleSlug: "hospitality-helper-waiter",
    salary: "UAE AED 1,500-2,800 / Qatar QAR 1,500-2,800 / Saudi SAR 1,800-3,000 monthly",
    salaryNote: "Indicative ordinary range before role-specific service charges, tips or employer benefits where applicable.",
    summary: "Support restaurants, hotels or catering operations with guest service, table preparation, food-running, cleaning and general hospitality duties.",
    duties: ["Prepare tables or service areas", "Assist food and beverage service", "Keep guest areas clean", "Follow hygiene rules", "Provide polite customer service"],
    requirements: ["Hospitality experience helpful", "Good presentation and communication", "Ability to work shifts", "Food-safety training where required", "Employer selection and destination work-authorization eligibility"],
  },
  {
    country: "Gulf Countries",
    countrySlug: "gulf",
    region: "Gulf / Middle East",
    role: "Light / Heavy Driver",
    roleSlug: "driver",
    salary: "UAE AED 2,500-4,500 / Qatar QAR 2,500-4,500 / Saudi SAR 2,500-4,500 monthly",
    salaryNote: "Indicative range; vehicle category, licence, route, overtime and employer package determine final pay.",
    summary: "Drive company, delivery or commercial vehicles safely, maintain route and vehicle records and comply with employer and local road requirements.",
    duties: ["Inspect assigned vehicle", "Drive approved routes", "Maintain delivery or trip records", "Keep vehicle reasonably clean", "Report defects and incidents"],
    requirements: ["Relevant driving experience", "Required licence or conversion eligibility", "Safe driving record", "Ability to meet destination transport standards", "Employer selection and destination work-authorization eligibility"],
  },
];

export function getSponsorshipJob(countrySlug: string, roleSlug: string) {
  return SPONSORSHIP_JOBS.find(
    (job) => job.countrySlug === countrySlug && job.roleSlug === roleSlug,
  );
}

export function sponsorshipCountries() {
  return Array.from(
    new Map(
      SPONSORSHIP_JOBS.map((job) => [
        job.countrySlug,
        { slug: job.countrySlug, name: job.country, region: job.region },
      ]),
    ).values(),
  );
}
