export type VisaTypeGuide = {
  name: string;
  purpose: string;
  details: string;
};

export type VisaCountryGuide = {
  country: string;
  slug: string;
  region: string;
  authority: string;
  officialUrl: string;
  overview: string;
  entryNote: string;
  visaTypes: VisaTypeGuide[];
};

const type = (name: string, purpose: string, details: string): VisaTypeGuide => ({
  name,
  purpose,
  details,
});

export const VISA_GUIDES: VisaCountryGuide[] = [
  {
    country: "United States",
    slug: "united-states",
    region: "North America",
    authority: "U.S. Department of State / U.S. Citizenship and Immigration Services",
    officialUrl: "https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/all-visa-categories.html",
    overview: "The United States separates temporary nonimmigrant visas from immigrant visas for permanent residence. The correct category depends on the exact purpose of travel, employment, study, family relationship or immigration basis.",
    entryNote: "Many employment categories require an approved employer petition before the visa interview. A visa allows travel to a U.S. port of entry; final admission is decided by U.S. border authorities.",
    visaTypes: [
      type("B-1 Business Visitor", "Temporary business activity", "For qualifying business meetings, negotiations, conferences and other permitted business-visitor activities. It does not authorize ordinary U.S. employment."),
      type("B-2 Tourist / Visitor", "Tourism, family visits and certain medical visits", "For temporary tourism, holidays, family visits and other permitted visitor purposes. Employment and regular academic study are not permitted."),
      type("F-1 / F-2", "Academic study and dependants", "F-1 is the main academic student category. Eligible spouse and children may use F-2. SEVIS and an approved school are normally part of the process."),
      type("M-1 / M-2", "Vocational or non-academic study", "For vocational or other recognized non-academic study. Dependants may qualify for M-2."),
      type("J-1 / J-2", "Exchange visitor programmes", "For approved exchange programmes such as trainees, interns, scholars, teachers and certain other exchange categories. J-2 is for eligible dependants."),
      type("H-1B", "Specialty occupation employment", "Employer-petition route for qualifying specialty occupations, subject to eligibility, petition requirements and any applicable cap or exemption rules."),
      type("H-2A", "Temporary agricultural work", "Employer-sponsored temporary agricultural worker category. Labour certification and USCIS petition stages generally come before the visa application."),
      type("H-2B", "Temporary non-agricultural work", "Employer-sponsored temporary or seasonal non-agricultural work category, subject to labour certification, petition rules and numerical limits."),
      type("H-3", "Trainee / special education exchange", "For certain training programmes that are not primarily employment and qualifying special-education exchange visitors."),
      type("L-1 / L-2", "Intra-company transfer", "For qualifying managers, executives or specialised-knowledge employees transferring within a related corporate group. Eligible dependants may use L-2."),
      type("O / P / Q", "Extraordinary ability, performers and cultural exchange", "Specialised temporary categories for extraordinary ability, athletes, entertainers, performers and certain international cultural exchange programmes."),
      type("R-1", "Religious worker", "For qualifying temporary religious workers sponsored by eligible religious organisations."),
      type("E-1 / E-2", "Treaty trader / treaty investor", "Available only to nationals of qualifying treaty countries and subject to the relevant trade or investment requirements."),
      type("K-1 / K-3", "Fiancé(e) or spouse-related immigration", "K-1 is for an eligible fiancé(e) of a U.S. citizen. K-3 is a spouse-related category used in limited circumstances."),
      type("Family-Sponsored Immigrant Visas", "Permanent residence through qualifying family", "Includes immediate-relative and family-preference categories such as IR, CR and F categories, depending on the qualifying relationship and petitioner."),
      type("Employment-Based Immigrant Visas", "Permanent residence through employment or investment", "Includes employment-based preference categories such as EB-1, EB-2, EB-3, certain special immigrants and qualifying investor routes."),
      type("Diversity Visa", "Diversity immigrant programme", "Annual programme for eligible applicants from qualifying countries, subject to official registration, selection and statutory eligibility rules."),
      type("C / D Crew and Transit Categories", "Transit and crew travel", "Used for qualifying transit and crewmember purposes. These categories do not replace a work visa for ordinary U.S. employment."),
    ],
  },
  {
    country: "Canada",
    slug: "canada",
    region: "North America",
    authority: "Immigration, Refugees and Citizenship Canada (IRCC)",
    officialUrl: "https://www.canada.ca/en/immigration-refugees-citizenship/services.html",
    overview: "Canada uses a combination of visas, electronic travel authorizations, work permits, study permits and permanent-residence programmes. A work permit or study permit is not itself a visa, although a visa or eTA may also be issued or required for travel.",
    entryNote: "Work and study applications are normally made through IRCC. Biometrics, medical examinations, employer documents or provincial requirements may apply depending on the programme.",
    visaTypes: [
      type("Temporary Resident Visa (Visitor Visa)", "Tourism, family visits and business visits", "For visa-required foreign nationals travelling temporarily to Canada for an eligible visitor purpose. Visitor status does not generally authorize employment."),
      type("Electronic Travel Authorization (eTA)", "Air travel for eligible visa-exempt travellers", "Electronic travel authorization for eligible visa-exempt travellers flying to or transiting through Canada. Eligibility depends on nationality and travel document."),
      type("Transit Visa", "Transit through Canada", "For certain visa-required travellers passing through Canada for a short transit without a regular visit."),
      type("Super Visa", "Parents and grandparents", "Longer-visit route for eligible parents and grandparents of Canadian citizens or permanent residents, subject to insurance and other requirements."),
      type("Employer-Specific Work Permit", "Work for a named employer", "Authorizes work under conditions stated on the permit. Depending on the job, an LMIA or an LMIA-exempt offer and employer compliance steps may be required."),
      type("Open Work Permit", "Work for eligible employers without one named employer", "Available only in specific situations, such as certain spouses, graduates or other eligible groups. It is not available to every applicant."),
      type("International Experience Canada", "Youth mobility work routes", "Working Holiday, Young Professionals and International Co-op routes for citizens of participating countries who meet programme rules."),
      type("Post-Graduation Work Permit", "Work after eligible Canadian study", "For graduates of eligible designated learning institutions who meet current PGWP requirements."),
      type("Study Permit", "Academic or vocational study", "Required for many study programmes lasting longer than six months. Applicants normally need admission from an eligible institution and must meet financial and other requirements."),
      type("Temporary Resident Permit", "Exceptional temporary entry or stay", "Discretionary document for certain people who are otherwise inadmissible or do not meet ordinary immigration requirements but have a justified temporary need."),
      type("Express Entry Permanent Residence", "Economic permanent residence", "Electronic selection system used for eligible federal economic programmes, subject to current eligibility, ranking and invitation rules."),
      type("Provincial Nominee Program", "Permanent residence through a province or territory", "Provinces and territories nominate eligible applicants under their own streams, followed by the federal permanent-residence stage."),
      type("Family Sponsorship", "Permanent residence through qualifying family", "For eligible spouses, partners, dependent children, parents or other qualifying relatives under Canadian family sponsorship rules."),
      type("Atlantic / Regional Economic Pathways", "Employer-supported or regional permanent residence", "Economic immigration routes for eligible workers in participating regions, subject to current programme availability and employer/community requirements."),
    ],
  },
  {
    country: "UAE",
    slug: "uae",
    region: "Gulf",
    authority: "UAE Federal Authority for Identity, Citizenship, Customs and Port Security / relevant emirate authority",
    officialUrl: "https://u.ae/en/information-and-services/visa-and-emirates-id/types-of-visas",
    overview: "The UAE has short-stay visit and tourist visas, work-related entry and residence routes, family and student residence, and longer-term self-sponsored residence categories such as Green, Golden and Blue visas.",
    entryNote: "Employment normally requires employer-led labour and residence steps. Depending on the emirate, applications may be handled by federal or emirate-level authorities.",
    visaTypes: [
      type("Tourist Visa", "Tourism and short visits", "For eligible visitors who are not using visa-free entry or visa on arrival. It may be arranged through approved channels such as airlines, hotels or travel agencies depending on the case."),
      type("Visit Visa", "Family, friends and eligible visit purposes", "Short-stay visit route. The specific sponsor, duration and entry conditions depend on the visit category."),
      type("Jobseeker Visit Visa", "Job search", "Self-sponsored visit route for eligible applicants seeking employment opportunities. It does not itself authorize employment."),
      type("Visit Visa to Explore Investment Opportunities", "Business and investment exploration", "For eligible individuals exploring business or investment opportunities before establishing residence or a business."),
      type("Standard Work / Residence Visa", "Employer-sponsored employment", "Main employer-linked route for many government and private-sector employees. Labour approval and residence steps are normally coordinated by the employer."),
      type("Domestic Worker Residence", "Domestic employment", "Residence and work route for eligible domestic workers under the applicable domestic worker sponsorship framework."),
      type("Green Visa", "Skilled work, freelancing or self-employment", "Longer-term self-sponsored residence for eligible skilled employees, freelancers, self-employed persons or investors meeting the official criteria."),
      type("Golden Visa", "Long-term residence for qualifying talent or investment", "Long-term residence for qualifying investors, entrepreneurs, scientists, exceptional talents, outstanding students and other eligible categories."),
      type("Blue Visa", "Long-term environmental contribution residence", "Long-term residence route for qualifying individuals with exceptional contributions to environmental protection and sustainability."),
      type("Student Residence Visa", "Study", "Residence route for students enrolled with qualifying UAE educational institutions, usually sponsored by the institution or an eligible family sponsor."),
      type("Family Residence Visa", "Family sponsorship", "Residents who meet the requirements may sponsor qualifying spouse, children or other family members under applicable rules."),
      type("Retirement Residence", "Residence after retirement", "Longer-term residence option for eligible retirees who meet the relevant financial and other requirements."),
      type("Residence for Working Outside the UAE", "Remote work residence", "Residence route for eligible people employed outside the UAE who meet the required income and employment criteria."),
      type("Transit Visa", "48- or 96-hour transit", "Airline-sponsored transit options for eligible travellers passing through the UAE."),
      type("Medical Visa / Entry Permit", "Medical treatment", "For qualifying patients travelling for medical treatment through an approved medical sponsor or facility."),
      type("GCC Resident eVisa", "Visit by eligible GCC residents", "Electronic entry route for eligible residents of GCC countries, subject to profession, residence and passport conditions."),
    ],
  },
  {
    country: "Qatar",
    slug: "qatar",
    region: "Gulf",
    authority: "Qatar Ministry of Interior / Hayya",
    officialUrl: "https://portal.moi.gov.qa/qatarvisas/",
    overview: "Qatar uses visit, tourist, work and residence permits, with the Hayya platform handling several visitor entry categories and the Ministry of Interior handling work, residence and related immigration services.",
    entryNote: "Employer-sponsored work cases normally involve the employer or sponsor. Visitor categories do not authorize ordinary employment unless the status is lawfully changed or the correct work permission is obtained.",
    visaTypes: [
      type("Hayya Tourist Visa", "Tourism", "Electronic visitor entry category for eligible international visitors applying through the Hayya platform."),
      type("GCC Resident Entry Visa", "Visit by eligible GCC residents", "Hayya entry route for eligible residents of Gulf Cooperation Council countries."),
      type("GCC Citizen Companion Entry Visa", "Visit while accompanying a GCC citizen", "Hayya category for eligible companions of GCC citizens."),
      type("Electronic Travel Authorization Entry", "Eligible ETA-based visit", "Hayya entry category for applicants who qualify under the electronic travel authorization rules."),
      type("Visa on Arrival", "Short visit", "Available to eligible nationalities subject to current conditions and entry requirements."),
      type("Work Visa / Work Entry Visa", "Employer-sponsored employment", "Employer-linked entry route used before employment residence procedures. Work authorization and residence steps are normally coordinated by the sponsor."),
      type("Work Residence Permit", "Long-term employment residence", "Residence status issued after required work, medical, biometric and identity procedures are completed."),
      type("Family Visit Visa", "Short family visit", "For eligible relatives visiting a resident. Sponsor and relationship documentation requirements apply."),
      type("Family Residence Permit", "Family joining", "For eligible dependants of qualifying residents, subject to sponsor, income, accommodation and relationship requirements."),
      type("Business / Official Visit", "Business or official activities", "Short-stay entry for qualifying business or official purposes under the applicable sponsor or invitation arrangements."),
      type("Student Residence", "Study", "Residence route for eligible international students sponsored or supported by a recognized educational institution."),
    ],
  },
  {
    country: "Kuwait",
    slug: "kuwait",
    region: "Gulf",
    authority: "Kuwait Ministry of Interior / Kuwait Government Online",
    officialUrl: "https://e.gov.kw/sites/kgoenglish/Pages/Services/MOI/WorkResidenceArticle18.aspx",
    overview: "Kuwait immigration uses entry visas and residence categories linked to the reason for stay, including government work, private-sector work, domestic work, family residence and visit categories.",
    entryNote: "Employment and family residence are generally sponsor-based. Article numbers are commonly used to identify residence categories and may be referenced in official procedures.",
    visaTypes: [
      type("Tourist / Visit Visa", "Tourism and short visits", "Short-stay visitor route subject to nationality, sponsor and current entry rules."),
      type("Family Visit Visa", "Visit relatives", "Entry visa for qualifying relatives of Kuwaiti citizens or residents, supported by relationship and sponsor documents."),
      type("Commercial / Business Visit", "Business visit", "Short entry for qualifying commercial or business activities based on an eligible Kuwaiti sponsor or entity."),
      type("Medical Treatment Visit", "Medical treatment", "Visit category for qualifying medical-treatment purposes under the applicable sponsorship and documentation rules."),
      type("Government Work Residence - Article 17", "Government-sector employment", "Residence route for qualifying foreign employees in the government sector."),
      type("Private Sector Work Residence - Article 18", "Private-sector employment", "Main private-sector work residence category, based on an employer sponsor and work permit procedures."),
      type("Domestic Worker Residence - Article 20", "Domestic employment", "Sponsor-based residence category for eligible domestic workers."),
      type("Family / Dependant Residence - Article 22", "Family joining", "Residence category for qualifying dependants of eligible residents, subject to sponsor and income rules."),
      type("Temporary Government Contract Work Visa", "Temporary government contract work", "Entry/work route for qualifying workers engaged under temporary government contracts."),
      type("Temporary Residence / Visit Extension", "Extend an eligible temporary stay", "Procedure for certain visitors who qualify to extend temporary residence or visit status."),
    ],
  },
  {
    country: "Bahrain",
    slug: "bahrain",
    region: "Gulf",
    authority: "Nationality, Passports and Residence Affairs (NPRA) / Labour Market Regulatory Authority (LMRA)",
    officialUrl: "https://www.npra.gov.bh/en/services/visas-residence-permit/",
    overview: "Bahrain has eVisas and visit visas, work permits and residence, family residence, student residence, self-sponsorship residence and Golden Residency categories.",
    entryNote: "Work permits for foreign employees are normally linked to LMRA and employer processes. Visit visas do not authorize employment.",
    visaTypes: [
      type("eVisa / Visit Visa", "Tourism and eligible visits", "Electronic or sponsored visitor entry for eligible nationalities and purposes."),
      type("Online Multiple-Entry Visa", "Repeated short visits", "Multiple-entry visitor route for qualifying applicants, subject to NPRA requirements and validity rules."),
      type("Family Visit Visa", "Visit relatives", "For qualifying relatives of Bahraini citizens or residents, supported by sponsor and relationship documents."),
      type("Business / Sponsored Visit", "Business and sponsored short visits", "Short-stay category for qualifying commercial or sponsored purposes."),
      type("Work Permit and Employment Residence", "Employment", "Employer-linked work and residence route processed under LMRA/NPRA requirements."),
      type("Dependant / Family Residence", "Family joining", "Residence for qualifying spouse, children, parents or other eligible family members under the applicable sponsor rules."),
      type("Student Residence Permit", "Study", "Residence category for qualifying students enrolled with eligible educational institutions."),
      type("Golden Residency", "Long-term residence", "Long-term residence route for eligible property owners, qualifying residents, retirees and other categories under current rules."),
      type("Self-Sponsorship Residence - Investor", "Investment", "Self-sponsored residence route for eligible investors."),
      type("Self-Sponsorship Residence - Property Owner", "Residence through qualifying property ownership", "Self-sponsored residence for qualifying foreign property owners."),
      type("Self-Sponsorship Residence - Retiree", "Retirement", "Self-sponsored residence for eligible retired foreign nationals."),
      type("Foreign Employees of GCC Companies", "Employment linked to a GCC company", "Special visa/residence route for qualifying foreign employees of GCC-based companies."),
    ],
  },
  {
    country: "Oman",
    slug: "oman",
    region: "Gulf",
    authority: "Royal Oman Police eVisa",
    officialUrl: "https://evisa.rop.gov.om/types-of-visa",
    overview: "Oman's eVisa system groups visas into Resident Sponsored, Resident Unsponsored, Visit Sponsored and Visit Unsponsored classes, with individual subtypes selected according to nationality and purpose.",
    entryNote: "The exact visa subclass available to a person depends on nationality, sponsor, purpose and residence status. Use the ROP eligibility tool for the current subclass list.",
    visaTypes: [
      type("Visit Unsponsored Visa", "Tourism or eligible short visit", "Visit visa class available without an Omani resident sponsor for eligible travellers and purposes."),
      type("Visit Sponsored Visa", "Sponsored family, business or other visit", "Visit class supported by an eligible Omani sponsor, employer or organisation depending on the subtype."),
      type("Tourist eVisa", "Tourism", "Electronic tourism route for eligible nationalities under the current ROP visa eligibility rules."),
      type("GCC Resident Visit Visa", "Visit by eligible GCC residents", "Short-stay route for eligible residents of GCC countries, subject to current profession and residence rules."),
      type("Employment / Work Visa", "Employer-sponsored work", "Sponsor-based entry and residence pathway for qualifying foreign employees."),
      type("Family Joining / Family Residence", "Family reunification", "Sponsored residence category for eligible family members of qualifying residents."),
      type("Student Visa / Residence", "Study", "Sponsored study route for eligible students accepted by recognized educational institutions."),
      type("Investor / Resident Unsponsored Route", "Investment or qualifying independent residence", "Resident-unsponsored class for eligible applicants who qualify under the relevant investment or residence category."),
      type("Transit / Short Special-Purpose Visa", "Transit or defined short purpose", "ROP provides specific short-stay subclasses for qualifying transit or special purposes; the current eligibility tool determines the correct subclass."),
    ],
  },
  {
    country: "Australia",
    slug: "australia",
    region: "Oceania",
    authority: "Australian Department of Home Affairs",
    officialUrl: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-finder",
    overview: "Australia has visitor, study, work, skilled migration, employer-sponsored, family, humanitarian and other visa streams. Visa subclasses and programme availability change, so the Home Affairs visa finder should always be checked before applying.",
    entryNote: "Many skilled and employer-sponsored visas require an eligible occupation, skills assessment, nomination, sponsorship or expression of interest. Conditions vary significantly by subclass.",
    visaTypes: [
      type("Visitor Visa - Subclass 600", "Tourism, business visitor activity or family visit", "Main visitor visa with streams for tourism, business visitor activity and sponsored family visits."),
      type("Electronic Travel Authority - Subclass 601", "Short visits for eligible passport holders", "Electronic travel authority for eligible nationalities visiting for tourism or business visitor purposes."),
      type("eVisitor - Subclass 651", "Short visits for eligible European passport holders", "Electronic visitor permission for eligible passport holders for tourism or business visitor activity."),
      type("Transit Visa - Subclass 771", "Transit", "For certain travellers transiting Australia when a transit visa is required."),
      type("Student Visa - Subclass 500", "Study", "For eligible full-time international students enrolled in a registered course."),
      type("Student Guardian - Subclass 590", "Accompany a minor student", "For eligible parents, custodians or relatives providing care to an international student under the required age."),
      type("Training Visa - Subclass 407", "Occupational training", "For workplace-based occupational training or professional development under an approved sponsor."),
      type("Skills in Demand Visa - Subclass 482", "Temporary employer-sponsored skilled work", "Employer-sponsored temporary skilled work route under the current Skills in Demand framework."),
      type("Employer Nomination Scheme - Subclass 186", "Permanent employer-sponsored skilled migration", "Permanent residence pathway for eligible skilled workers nominated by an approved Australian employer."),
      type("Skilled Independent - Subclass 189", "Permanent skilled migration", "Points-tested permanent visa for eligible skilled applicants invited through SkillSelect."),
      type("Skilled Nominated - Subclass 190", "State/territory nominated permanent migration", "Points-tested permanent visa requiring nomination by an Australian state or territory."),
      type("Skilled Work Regional - Subclass 491", "Regional skilled provisional migration", "Points-tested provisional visa for eligible applicants nominated by a state/territory or sponsored by an eligible relative in regional Australia."),
      type("Skilled Employer Sponsored Regional - Subclass 494", "Regional employer-sponsored work", "Employer-sponsored provisional visa for eligible skilled positions in regional Australia."),
      type("Working Holiday / Work and Holiday - 417 / 462", "Holiday with incidental work", "Youth mobility visas for citizens of participating countries, subject to age, nationality and other programme rules."),
      type("Temporary Activity - Subclass 408", "Specific temporary activities", "For eligible participants in approved temporary activities, events, entertainment, research or other defined streams."),
      type("National Innovation Visa - Subclass 858", "Exceptional talent and innovation", "Permanent invitation-based route for exceptionally talented people in priority fields under current programme rules."),
      type("Partner Visas - 820/801 and 309/100", "Partner or spouse migration", "Temporary/permanent partner pathways depending on whether the applicant applies in or outside Australia."),
      type("Prospective Marriage - Subclass 300", "Fiancé(e) migration", "Temporary visa for eligible applicants intending to marry an Australian citizen, permanent resident or eligible New Zealand citizen."),
      type("Parent and Child Visas", "Family migration", "Multiple subclasses exist for eligible parents, children, adopted children and orphan relatives, with different waiting periods and criteria."),
      type("Refugee and Humanitarian Visas", "Protection and humanitarian resettlement", "Routes under Australia's refugee and humanitarian programme for eligible applicants."),
    ],
  },
  {
    country: "New Zealand",
    slug: "new-zealand",
    region: "Oceania",
    authority: "Immigration New Zealand",
    officialUrl: "https://www.immigration.govt.nz/process-to-apply/find-a-visa-tool/",
    overview: "New Zealand offers visitor, work, study, family and residence visas. Some work visas are employer-linked, while others are based on study, partnership, age or residence pathways.",
    entryNote: "Visa conditions control whether the holder may work, study or sponsor family. Applicants should use Immigration New Zealand's visa search for current eligibility and fees.",
    visaTypes: [
      type("Visitor Visa", "Tourism and family visits", "For eligible visitors staying temporarily. It normally does not permit New Zealand employment, although limited remote work for overseas clients may be allowed under current rules."),
      type("NZeTA", "Travel authorization for eligible visa-waiver travellers", "Electronic travel authority used by eligible travellers and some transit passengers instead of a visitor visa."),
      type("Business Visitor Visa", "Short business visits", "For eligible business visitor activities that do not amount to ordinary New Zealand employment."),
      type("Accredited Employer Work Visa", "Employer-linked work", "Main work visa for many applicants with an eligible job offer from an accredited employer."),
      type("Specific Purpose Work Visa", "Defined work purpose", "For applicants entering to complete a specific work-related purpose or event that meets the category rules."),
      type("Post Study Work Visa", "Work after eligible New Zealand study", "Allows eligible graduates to work after completing qualifying New Zealand study."),
      type("Working Holiday Visa", "Holiday with temporary work", "For eligible young citizens of countries that have a working-holiday agreement with New Zealand."),
      type("Partner of a Worker / Student Work Visa", "Work based on eligible partner relationship", "Available to qualifying partners of certain work or student visa holders, subject to the principal applicant's visa and current rules."),
      type("Fee Paying Student Visa", "Full-time study", "Main visa for international students paying tuition at an approved education provider."),
      type("Pathway / English Language / Other Student Visas", "Specialized study", "New Zealand also provides specific student categories for pathway study, English-language study, dependent children and other eligible education situations."),
      type("Skilled Migrant Category Resident Visa", "Skilled residence", "Residence pathway for eligible skilled people meeting the current skilled residence criteria."),
      type("Green List Straight to Residence / Work to Residence", "Priority occupation residence", "Residence pathways linked to eligible Green List occupations and required employment conditions."),
      type("Care Workforce Work to Residence", "Care workforce residence", "Residence pathway for eligible care-sector workers who meet the required work history and other criteria."),
      type("Investor / Business Residence", "Investment and business", "Residence categories exist for qualifying investors or business applicants, subject to current investment and programme requirements."),
      type("Partner / Parent / Dependent Child Residence", "Family residence", "Family residence routes for eligible partners, parents and dependent children of New Zealand citizens or residents."),
    ],
  },
  {
    country: "Chile",
    slug: "chile",
    region: "South America",
    authority: "Servicio Nacional de Migraciones (SERMIG)",
    officialUrl: "https://serviciomigraciones.cl/en/residencia-temporal-permit/",
    overview: "Chile distinguishes temporary visitor stay from temporary and permanent residence. The official temporary residence system contains multiple subcategories based on work, study, family, investment, humanitarian and other grounds.",
    entryNote: "Temporary residence applications are normally submitted through SERMIG's digital procedures. Foreign documents may require apostille/legalisation and translation under current rules.",
    visaTypes: [
      type("Permanencia Transitoria", "Tourism and other temporary visits", "Temporary stay status for visitors who do not intend to reside in Chile. Paid activity is generally restricted unless a specific authorization applies."),
      type("Temporary Residence - Family Reunification", "Join qualifying family", "For eligible applicants with qualifying family ties under Chilean immigration rules."),
      type("Temporary Residence - Lawful Remunerated Activities", "Employment or other paid activity", "For foreigners carrying out lawful paid activities in Chile under the relevant employment or service arrangement."),
      type("Temporary Residence - Students", "Study", "For students enrolled in state-recognized educational institutions. Current rules may allow limited work while studying."),
      type("Temporary Residence - Seasonal Workers", "Seasonal employment", "Special temporary residence subcategory for qualifying seasonal workers, with specific validity rules."),
      type("Temporary Residence - Persons under Gendarmería Custody", "Defined judicial/custodial situation", "Special residence subcategory for foreigners subject to the custody of Gendarmería de Chile."),
      type("Temporary Residence - Court-Ordered Presence", "Presence ordered by Chilean courts", "Special category for foreigners in Chile by order of national Courts of Justice."),
      type("Temporary Residence - Humanitarian Reasons", "Humanitarian residence", "Residence subcategory for applicants who meet the humanitarian criteria established by Chilean law."),
      type("Temporary Residence - International Agreements", "Residence under qualifying international agreements", "For people covered by qualifying international agreements."),
      type("Temporary Residence - Religious Persons", "Religious activity", "For members of recognized religious groups who meet the category requirements."),
      type("Temporary Residence - Medical Treatment", "Medical treatment", "For qualifying applicants who need residence in Chile for medical treatment."),
      type("Temporary Residence - Retirees or Rentiers", "Retirement or passive income", "For eligible retirees or people who qualify through recognized recurring income."),
      type("Temporary Residence - Former Permanent Residents", "Return after prior permanent residence", "For qualifying former holders of Chilean permanent residence."),
      type("Temporary Residence - Investors and Related Personnel", "Investment", "For eligible investors and related personnel meeting the programme requirements."),
      type("Temporary Residence - Multi-Entry Business Management", "Recurring business management", "For qualifying people who carry out business-management activity requiring multiple entries."),
      type("Temporary Residence - International Reciprocity / Mercosur", "Residence based on reciprocity agreements", "For eligible nationals covered by applicable Mercosur or other reciprocity arrangements."),
      type("Residencia Definitiva", "Permanent residence", "Permanent residence status for eligible temporary residents who meet the required residence and eligibility conditions."),
    ],
  },
  {
    country: "Peru",
    slug: "peru",
    region: "South America",
    authority: "Superintendencia Nacional de Migraciones / Ministry of Foreign Affairs",
    officialUrl: "https://www.gob.pe/migraciones",
    overview: "Peru uses temporary and resident immigration statuses based on the purpose of stay, including work, study, family, investment, business, retirement and other lawful activities.",
    entryNote: "Some resident visa applications can be initiated virtually or through the relevant Peruvian consulate. Exact procedures depend on whether the applicant is outside Peru or already holds lawful status in Peru.",
    visaTypes: [
      type("Tourist / Temporary Visitor", "Tourism and short visits", "Short-stay visitor status for eligible travellers. Ordinary paid employment is not authorized under tourist status."),
      type("Business Visa / Business Temporary Status", "Business activity", "For qualifying business visits that do not constitute local employment."),
      type("Worker Resident", "Employment", "Resident status for foreigners carrying out dependent or independent remunerated activity, including qualifying employment or service contracts."),
      type("Professional Resident", "Professional activity", "Resident route for eligible foreign professionals meeting applicable qualification and professional requirements."),
      type("Student Resident", "Study", "Resident status for eligible students enrolled in recognized educational or training programmes."),
      type("Family Resident", "Family reunification", "Resident status for qualifying family members of Peruvian citizens or lawful residents."),
      type("Spouse of Peruvian Resident Status", "Marriage to a Peruvian citizen", "Family-based residence route for eligible spouses under Peruvian migration rules."),
      type("Investor Resident", "Investment", "Resident status for qualifying investors meeting current investment and documentation requirements."),
      type("Rentista / Retiree Resident", "Retirement or qualifying passive income", "Residence for eligible retirees or people with qualifying permanent income from abroad."),
      type("Religious / Humanitarian / Special Categories", "Religious, humanitarian or special lawful stay", "Peru provides additional immigration statuses for specific humanitarian, religious, official and special circumstances."),
      type("Permanent / Indefinite Residence", "Long-term residence", "Long-term status available to eligible residents who meet the applicable residence and legal requirements."),
    ],
  },
  {
    country: "Singapore",
    slug: "singapore",
    region: "Asia",
    authority: "Immigration & Checkpoints Authority (ICA) / Ministry of Manpower (MOM)",
    officialUrl: "https://www.mom.gov.sg/passes-and-permits",
    overview: "Singapore uses entry visas and visit passes for travel, while employment is controlled through work passes issued by the Ministry of Manpower. Study and longer-term family residence use separate ICA passes.",
    entryNote: "A Singapore entry visa is not permission to work. Foreigners must hold the correct work pass before starting employment.",
    visaTypes: [
      type("Entry Visa / Short-Term Visit Pass", "Tourism, family and short visits", "Visa-required travellers may need an entry visa before travel. Admission and the length of stay are determined at the border through the visit pass."),
      type("Business Visitor / Short-Term Business Activity", "Eligible short business activity", "Certain business visits may be carried out as visitors, but local employment requires the appropriate work pass."),
      type("Employment Pass", "Professional, managerial or executive work", "For qualifying foreign professionals, managers, executives and technicians meeting salary and COMPASS requirements."),
      type("S Pass", "Skilled work", "For qualifying skilled foreign employees meeting current salary and quota requirements."),
      type("Work Permit for Migrant Worker", "Sector-specific skilled or semi-skilled work", "For eligible workers in approved sectors such as construction, manufacturing, marine shipyard, process or services."),
      type("Work Permit for Migrant Domestic Worker", "Domestic work", "For eligible foreign domestic workers sponsored by qualifying households."),
      type("EntrePass", "Entrepreneurship", "For eligible foreign entrepreneurs starting and operating qualifying innovative or venture-backed businesses."),
      type("Personalised Employment Pass / ONE Pass", "High-earning or top-talent work", "Special work-pass routes for qualifying high earners or top global talent under the current eligibility rules."),
      type("Training Employment Pass / Training Work Permit", "Training", "For eligible foreign trainees or students completing approved practical training."),
      type("Student's Pass", "Study", "For eligible international students accepted by approved Singapore educational institutions."),
      type("Dependant's Pass / Long-Term Visit Pass", "Family residence", "Family passes for eligible spouses, children, parents or other qualifying dependants of citizens, permanent residents or work-pass holders."),
      type("Permanent Residence", "Long-term residence", "Permanent residence may be available to eligible professionals, family members, students or investors under ICA-administered schemes."),
    ],
  },
  {
    country: "United Kingdom",
    slug: "united-kingdom",
    region: "Europe",
    authority: "UK Visas and Immigration (UKVI)",
    officialUrl: "https://www.gov.uk/browse/visas-immigration",
    overview: "The UK has separate visitor, work, study, family, settlement and protection routes. Many work routes require sponsorship by a licensed UK employer, while other categories are unsponsored.",
    entryNote: "Visa conditions vary by route. Applicants should check whether they need a visa, ETA or other permission and should verify the latest salary, sponsorship and English-language rules before applying.",
    visaTypes: [
      type("Standard Visitor Visa", "Tourism, family visits and eligible business activities", "For most short visits, usually up to six months, for tourism, family, limited business, medical treatment and other permitted visitor activities."),
      type("Marriage Visitor Visa", "Marriage or civil partnership without settlement", "For eligible people coming to marry or enter a civil partnership in the UK without intending to settle under that visa."),
      type("Transit Visa", "Airside or landside transit", "For visa-required travellers passing through the UK on the way to another country."),
      type("Skilled Worker Visa", "Sponsored skilled employment", "Main sponsored work route for eligible jobs with a licensed sponsor, subject to occupation, salary and other current requirements."),
      type("Health and Care Worker Visa", "Sponsored health and care employment", "Skilled Worker sub-route for eligible health and care professionals with an approved sponsor."),
      type("Global Business Mobility Routes", "Business transfer and expansion", "Sponsored routes for senior or specialist workers, graduate trainees, service suppliers, secondments and UK expansion workers."),
      type("Temporary Worker Routes", "Temporary sponsored work", "Includes eligible seasonal work, charity work, creative work, religious work, government-authorized exchange and international agreement routes."),
      type("Global Talent Visa", "Exceptional talent or promise", "Unsponsored route for eligible leaders or potential leaders in academia/research, arts/culture and digital technology."),
      type("High Potential Individual Visa", "Recent graduate from an eligible global university", "Unsponsored temporary work route for qualifying recent graduates of eligible universities."),
      type("Graduate Visa", "Post-study work", "Allows eligible UK graduates to stay and work after successfully completing an eligible UK course."),
      type("Student Visa", "Higher education and other eligible study", "For eligible international students sponsored by a licensed education provider."),
      type("Child Student Visa", "Independent school study", "For eligible children studying at independent schools in the UK."),
      type("Family Visa", "Join spouse, partner, child or parent", "For qualifying family relationships where the relevant UK family immigration route applies."),
      type("Youth Mobility Scheme", "Work and travel for eligible young nationals", "Temporary unsponsored route available to citizens of participating countries and territories who meet the age and eligibility rules."),
      type("UK Ancestry / BNO and Other Nationality Routes", "Special nationality or ancestry-based residence", "Specific routes exist for qualifying Commonwealth ancestry, British National (Overseas) status and other defined categories."),
      type("Indefinite Leave to Remain", "Settlement", "Permanent settlement may be available after qualifying residence under eligible immigration routes."),
      type("Asylum / Humanitarian Protection", "Protection", "Protection routes for people who meet the legal requirements for asylum or humanitarian protection."),
    ],
  },
  {
    country: "Germany",
    slug: "germany",
    region: "Europe",
    authority: "Federal Foreign Office / Make it in Germany",
    officialUrl: "https://www.make-it-in-germany.com/en/visa-residence/types",
    overview: "Germany uses Schengen short-stay visas for visits up to 90 days and national visas/residence permits for longer stays such as work, vocational training, study, job search, self-employment and family reunification.",
    entryNote: "Non-EU applicants normally obtain the appropriate national visa before entering for work or study, then apply for the relevant residence title after arrival when required.",
    visaTypes: [
      type("Schengen Visa - Type C", "Short visits", "For short stays up to 90 days in any 180-day period for tourism, family visits, business and other eligible purposes."),
      type("Airport Transit Visa - Type A", "Airport transit", "For certain nationalities transiting the international zone of a German airport without entering Schengen."),
      type("EU Blue Card", "Highly qualified employment", "Residence/work route for eligible graduates or comparable professionals with a qualifying job and salary."),
      type("Work Visa for Qualified Professionals", "Skilled employment", "For eligible applicants with a recognized vocational or academic qualification and a qualifying job offer."),
      type("Visa for Professionally Experienced Workers", "Employment based on experience", "For qualifying workers with recognized foreign vocational or academic qualifications and sufficient professional experience in eligible non-regulated occupations."),
      type("Recognition Partnership Visa", "Work while completing professional recognition", "Allows eligible applicants to work while completing the recognition process with an employer under a recognition partnership."),
      type("Opportunity Card", "Job search", "Points/qualification-based route allowing eligible applicants to enter Germany to search for qualified employment and undertake permitted trial or part-time work."),
      type("Vocational Training Visa", "Ausbildung / vocational training", "For applicants accepted into eligible vocational training or, in some cases, seeking a training place."),
      type("Student Visa", "University study", "For applicants admitted to eligible German higher education, including certain preparatory measures."),
      type("Research Visa / Residence", "Research", "For eligible researchers with a hosting agreement or qualifying research position."),
      type("Self-Employment / Freelance Visa", "Business or freelance activity", "For eligible entrepreneurs or freelancers who meet the economic, professional and financing requirements."),
      type("Family Reunification Visa", "Join spouse, children or eligible family", "National visa/residence route for qualifying family members of German citizens or lawful residents."),
      type("Language Course / School / Other Education Visas", "Language study and defined education", "Special national visa routes may apply to intensive language courses, school attendance and other qualifying education."),
    ],
  },
  {
    country: "France",
    slug: "france",
    region: "Europe",
    authority: "France-Visas / French Ministry for Europe and Foreign Affairs",
    officialUrl: "https://france-visas.gouv.fr/en/web/france-visas/",
    overview: "France uses Schengen short-stay visas and long-stay visas for stays over 90 days. Long-stay categories cover employment, study, family, private stay, entrepreneurship and other purposes.",
    entryNote: "France-Visas provides a visa wizard that determines the correct category and required documents. Some long-stay visas act as residence permits after online validation, while others require a residence permit application after arrival.",
    visaTypes: [
      type("Airport Transit Visa - Type A", "Airport transit", "For certain travellers transiting through the international zone of a French airport."),
      type("Schengen Short-Stay Visa - Type C", "Tourism, family, business and short visits", "For eligible stays up to 90 days in any 180-day period."),
      type("Long-Stay Visitor Visa", "Private stay without employment", "For eligible people staying more than 90 days for private or tourist reasons without working."),
      type("Salaried Employee / Temporary Worker Visa", "Employment", "Long-stay work route for qualifying employees with the required French work authorization where applicable."),
      type("Talent Residence / Talent Passport Routes", "Highly skilled, innovative, artistic or investment activity", "Long-stay residence routes for qualifying high-skilled workers, researchers, founders, investors, artists and other talent categories."),
      type("Student Visa", "Study", "Short- or long-stay student route depending on course duration, with an admission/enrolment basis."),
      type("Researcher / Scientist", "Research", "For qualifying researchers hosted by eligible French research or higher-education institutions."),
      type("Entrepreneur / Liberal Profession", "Self-employment or business", "Long-stay route for eligible entrepreneurs, business creators and independent professionals."),
      type("Family of French National", "Join French spouse, parent or child", "Family route varies by relationship and intended length of stay, including long-stay residence pathways."),
      type("Family Reunification / Family of Resident", "Join eligible foreign resident", "Long-stay family routes apply to qualifying family members under French and EU rules."),
      type("Working Holiday", "Youth mobility", "Available to eligible nationals of participating countries under bilateral working-holiday arrangements."),
      type("Medical / Humanitarian / Special Visas", "Medical or exceptional purpose", "Special short- or long-stay categories may apply depending on the applicant's circumstances and official decision."),
    ],
  },
  {
    country: "Italy",
    slug: "italy",
    region: "Europe",
    authority: "Italian Ministry of Foreign Affairs and International Cooperation",
    officialUrl: "https://vistoperitalia.esteri.it/home/en",
    overview: "Italy issues airport transit visas, Schengen short-stay visas and national long-stay visas. Long stays are tied to a specific purpose such as employment, self-employment, study, family or elective residence.",
    entryNote: "For many long-stay categories, a national Type D visa is used to enter Italy and the applicant then applies for the relevant residence permit after arrival.",
    visaTypes: [
      type("Airport Transit Visa - Type A", "Airport transit", "For certain nationals transiting through the international zone of an Italian airport."),
      type("Uniform Schengen Visa - Type C", "Short visit", "For stays up to 90 days in any 180-day period for tourism, business, family visit, cultural, sport and other eligible short-stay purposes."),
      type("Limited Territorial Validity Visa", "Restricted Schengen travel", "Visa valid only for specified Schengen territory in exceptional or defined circumstances."),
      type("National Visa - Type D", "Long stay", "General long-stay entry visa used for residence purposes exceeding 90 days."),
      type("Subordinate Employment Visa", "Employment", "For qualifying employees with the required employment authorization and employer documentation."),
      type("Self-Employment Visa", "Self-employment", "For eligible entrepreneurs, professionals and self-employed applicants who meet sector and authorization requirements."),
      type("EU Blue Card / Highly Qualified Work", "Highly qualified employment", "Work and residence route for eligible highly qualified employees meeting current qualification and salary criteria."),
      type("Study Visa", "University, training or other eligible study", "For applicants accepted into eligible Italian education or training programmes."),
      type("Research Visa", "Scientific research", "For eligible researchers hosted by qualifying research institutions."),
      type("Family Reunification Visa", "Join qualifying family", "For eligible family members of Italian citizens or lawful residents under the applicable family rules."),
      type("Investor Visa", "Investment", "For eligible investors making qualifying investments under Italy's investor programme."),
      type("Elective Residence Visa", "Long-term residence without employment", "For eligible applicants with stable independent income who intend to reside in Italy without working."),
      type("Religious / Mission / Special Purpose Visas", "Religious, mission or other defined purposes", "Italy provides additional national visa categories for specific lawful purposes listed in the official Visa for Italy portal."),
      type("Working Holiday", "Youth mobility", "Available under bilateral agreements to eligible citizens of participating countries."),
    ],
  },
  {
    country: "Netherlands",
    slug: "netherlands",
    region: "Europe",
    authority: "Immigration and Naturalisation Service (IND)",
    officialUrl: "https://ind.nl/en/residence-permits",
    overview: "The Netherlands uses Schengen short-stay visas and residence permits for work, study, family, exchange, entrepreneurship and other longer stays. Some applicants also need an MVV provisional residence visa before travel.",
    entryNote: "For many long-stay applicants, the MVV and residence permit are requested together. Employers or educational institutions may need to be recognized sponsors for certain categories.",
    visaTypes: [
      type("Schengen Short-Stay Visa", "Tourism, business and family visits", "For visa-required visitors staying up to 90 days in any 180-day period."),
      type("Airport Transit Visa", "Airport transit", "For certain nationals passing through the international transit area of a Dutch airport."),
      type("MVV - Provisional Residence Permit", "Long-stay entry", "Entry visa used by many applicants who need to travel to the Netherlands to collect or activate a residence permit."),
      type("Highly Skilled Migrant", "Highly skilled employment", "Employer-sponsored residence route through a recognized sponsor for qualifying employees meeting current salary and eligibility criteria."),
      type("GVVA Single Permit", "Paid employment", "Combined residence and work authorization for qualifying employees who require both permissions."),
      type("EU Blue Card", "Highly qualified employment", "Residence permit for qualifying highly skilled workers meeting EU Blue Card requirements."),
      type("Intra-Corporate Transfer", "Corporate transfer", "Residence route for qualifying managers, specialists and trainee employees transferred within a multinational group."),
      type("Seasonal Work", "Temporary agricultural work", "Residence/work route for eligible seasonal agricultural employment for a limited period."),
      type("Start-up / Self-Employed", "Entrepreneurship", "Separate residence routes for qualifying innovative start-ups and self-employed entrepreneurs."),
      type("Orientation Year", "Post-study or research job search", "Temporary residence allowing eligible graduates and researchers to seek work or start a business."),
      type("Study Residence Permit", "Study", "For eligible international students sponsored by a recognized educational institution."),
      type("Research Residence Permit", "Research", "For qualifying researchers under the relevant EU/research framework."),
      type("Family and Partner Residence", "Family reunification", "Residence routes for qualifying spouses, partners, children and other eligible family members."),
      type("Au Pair / Cultural Exchange", "Exchange", "Residence route through a recognized exchange sponsor for eligible au pairs and exchange participants."),
      type("Medical / Humanitarian / Private Grounds", "Special residence circumstances", "Additional residence permits exist for medical treatment, humanitarian circumstances and other defined legal grounds."),
    ],
  },
  {
    country: "Switzerland",
    slug: "switzerland",
    region: "Europe",
    authority: "State Secretariat for Migration (SEM)",
    officialUrl: "https://www.schweiz-kenia.eda.admin.ch/en/visa-entry-to-and-residence-in-switzerland",
    overview: "Switzerland participates in Schengen for short stays and uses national long-stay visas and residence permits for work, study, family and other residence purposes.",
    entryNote: "Third-country nationals generally face labour-market and qualification requirements for work. The canton and federal authorities may both be involved in work and residence approvals.",
    visaTypes: [
      type("Airport Transit Visa - Type A", "Airport transit", "For certain visa-required travellers transiting through the international zone of a Swiss airport."),
      type("Schengen Visa - Type C", "Tourism, family, business and short visits", "For short stays up to 90 days in any 180-day period."),
      type("National Visa - Type D", "Long stay", "Entry visa for stays longer than 90 days, linked to an approved residence purpose."),
      type("Work Visa / Residence Permit", "Employment", "For qualifying employees after the required Swiss labour-market and cantonal/federal authorizations are approved."),
      type("Highly Qualified Specialist / Management Work", "Skilled employment", "Third-country work admissions generally prioritize highly qualified managers, specialists and other skilled professionals subject to quotas and labour-market rules."),
      type("Study Visa / Residence Permit", "Study", "For eligible students admitted to recognized Swiss educational institutions and able to meet financial and other residence requirements."),
      type("Family Reunification", "Join qualifying family", "Residence route for eligible family members of Swiss citizens or lawful residents, subject to relationship and accommodation requirements."),
      type("Business / Conference Short-Stay", "Business visitor activity", "Usually handled under a Schengen short-stay visa when the activity does not constitute Swiss employment."),
      type("Medical Treatment Short-Stay", "Medical care", "Schengen short-stay route can be used for qualifying medical treatment, supported by medical and financial documentation."),
    ],
  },
  {
    country: "Sweden",
    slug: "sweden",
    region: "Europe",
    authority: "Swedish Migration Agency",
    officialUrl: "https://www.migrationsverket.se/en/you-want-to-apply.html",
    overview: "Sweden uses Schengen visas for short visits and residence permits for work, study, family, self-employment and longer visits. Most non-EU/EEA citizens need a permit before starting work or long-term study.",
    entryNote: "Work permits are commonly employer-linked, and the employer begins or supports parts of the application. Applicants may also need to show a passport, provide fingerprints and collect a residence permit card.",
    visaTypes: [
      type("Schengen Visa", "Visits up to 90 days", "For tourism, family visits, business and other eligible short stays when a visa is required."),
      type("Visitor's Residence Permit", "Visit longer than 90 days", "For eligible people visiting Sweden for more than 90 days without taking up ordinary residence for work or study."),
      type("Employee Work Permit", "Employment", "For eligible non-EU/EEA workers with a qualifying job offer meeting current employment and salary requirements."),
      type("EU Blue Card", "Highly qualified employment", "Residence/work permit for eligible highly qualified workers meeting current qualification and salary conditions."),
      type("ICT Permit", "Intra-corporate transfer", "For qualifying managers, specialists or trainees transferred within a corporate group."),
      type("Self-Employed Residence Permit", "Business / self-employment", "For eligible entrepreneurs who own or operate a qualifying business and meet financial and business requirements."),
      type("Seasonal Work Permit", "Seasonal employment", "For eligible seasonal workers in approved sectors and employment arrangements."),
      type("Highly Qualified Job-Seeker Permit", "Look for work or explore a business", "For certain applicants with advanced qualifications who meet the rules to seek highly qualified employment or explore starting a business."),
      type("Residence Permit for Studies", "Higher education, doctoral or other qualifying study", "For eligible students admitted to qualifying study programmes. Separate study categories apply to higher education, doctoral study and other education."),
      type("Research Permit", "Research", "For eligible researchers hosted by an approved research principal or institution."),
      type("Family Residence Permit", "Live with partner, parent or family", "For qualifying family members joining Swedish citizens or lawful residents."),
      type("Permanent Residence", "Long-term residence", "May be available to eligible applicants after meeting the relevant duration, livelihood and other statutory requirements."),
    ],
  },
  {
    country: "Norway",
    slug: "norway",
    region: "Europe",
    authority: "Norwegian Directorate of Immigration (UDI)",
    officialUrl: "https://www.udi.no/en/want-to-apply/",
    overview: "Norway uses Schengen visitor visas for short visits and residence permits for work, study, family immigration and other longer stays.",
    entryNote: "The correct residence permit depends on the applicant's qualifications, job, study programme or family relationship. Some permits count toward permanent residence and others do not.",
    visaTypes: [
      type("Visitor Visa - Schengen", "Visits up to 90 days", "For eligible short visits to Norway and the Schengen area, including tourism and family visits."),
      type("Skilled Worker Residence Permit", "Skilled employment", "For eligible workers with vocational training, higher education or special qualifications and a qualifying job offer."),
      type("Seasonal Worker Residence Permit", "Seasonal employment", "For qualifying seasonal jobs under the applicable labour and immigration requirements."),
      type("Self-Employed / Assignment Work Routes", "Business or contracted work", "Special work-residence routes exist for certain self-employed persons, service providers and employees on assignments, subject to UDI rules."),
      type("Study Permit", "University, vocational and other eligible study", "For full-time study at eligible institutions. Many student permits allow limited part-time work under stated conditions."),
      type("Job-Seeker / Post-Study Routes", "Seek skilled work after qualifying study or training", "Available in specific circumstances to eligible applicants who meet UDI's education and status requirements."),
      type("Family Immigration Permit", "Join spouse, partner, children or other qualifying family", "Family residence route with relationship, income and other requirements depending on the sponsor and relationship."),
      type("Residence under EU/EEA Rules", "EU/EEA free movement", "Separate registration and residence-card rules apply to EU/EEA citizens and qualifying family members."),
      type("Protection / Asylum", "International protection", "For people who meet the legal requirements for refugee protection or other protected status."),
    ],
  },
  {
    country: "Denmark",
    slug: "denmark",
    region: "Europe",
    authority: "Danish Immigration Service / SIRI - New to Denmark",
    officialUrl: "https://www.nyidanmark.dk/en-GB/You-want-to-apply",
    overview: "Denmark uses Schengen visas for short visits and residence/work permits for employment, study, family, PhD, business and other long stays. EU/EEA and Nordic citizens follow separate rules.",
    entryNote: "Many work schemes are administered by the Danish Agency for International Recruitment and Integration (SIRI), while family reunification and visas may be handled by the Danish Immigration Service.",
    visaTypes: [
      type("Schengen Short-Stay Visa", "Visits up to 90 days", "For tourism, family visits, business and other eligible short stays when a visa is required."),
      type("Positive List Work Scheme", "Employment in shortage occupations", "Residence/work route for eligible applicants offered a job on the current Positive List."),
      type("Pay Limit Scheme", "High-salary employment", "Work route for qualifying job offers meeting the current minimum salary and employment conditions."),
      type("Fast-track Scheme", "Certified-company sponsored work", "Flexible work/residence scheme for eligible employees hired by SIRI-certified companies."),
      type("Researcher / Guest Researcher", "Research", "Work/residence route for qualifying researchers and guest researchers."),
      type("Start-up Denmark", "Entrepreneurship", "Residence/work route for eligible foreign entrepreneurs with an approved innovative business idea."),
      type("Trainee / Special Individual Qualifications / Other Work Schemes", "Specialized work", "Denmark provides additional work routes for qualifying trainees, people with special individual qualifications and certain sector-specific roles."),
      type("Student Residence Permit", "Higher education and other qualifying study", "For eligible students admitted to approved Danish educational programmes."),
      type("PhD Residence Permit", "Doctoral study", "Separate residence route for applicants participating in a Danish PhD programme."),
      type("Family Reunification", "Join spouse, partner or family", "Residence route for qualifying family members, subject to the detailed Danish family rules."),
      type("Accompanying Family", "Family of work/study permit holder", "Eligible family members may apply to accompany qualifying workers or students."),
      type("EU/EEA Residence", "EU free movement", "Separate EU residence rules apply to eligible EU/EEA/Swiss citizens and family members."),
    ],
  },
  {
    country: "Finland",
    slug: "finland",
    region: "Europe",
    authority: "Finnish Immigration Service (Migri) / Ministry for Foreign Affairs for visas",
    officialUrl: "https://migri.fi/en/applying-for-a-residence-permit",
    overview: "Finland uses Schengen visas for short visits and residence permits for work, study, family, research, entrepreneurship and other stays longer than 90 days.",
    entryNote: "Most first residence permits for work or study are applied for before travelling to Finland. Applicants normally prove identity at a Finnish mission or service point after submitting the application.",
    visaTypes: [
      type("Schengen Visa", "Short visit", "For visa-required travellers visiting Finland for up to 90 days in any 180-day period for tourism, family, business or other eligible purposes."),
      type("Seasonal Work Visa", "Seasonal work under 90 days for visa-required nationals", "For certain seasonal jobs lasting under three months where a visa is required."),
      type("Residence Permit for an Employed Person", "Employment", "Main work residence route for many jobs, with labour-market and employer conditions depending on the occupation."),
      type("Specialist Residence Permit", "Specialist employment", "For eligible experts and specialists meeting current salary and job requirements."),
      type("EU Blue Card", "Highly qualified employment", "For eligible highly qualified workers meeting EU Blue Card conditions."),
      type("Seasonal Work Residence Permit", "Seasonal employment over longer periods", "For eligible seasonal employment lasting longer than the short visa period, subject to seasonal-work rules."),
      type("Entrepreneur / Start-up Entrepreneur Permit", "Business", "Separate residence routes for eligible entrepreneurs and approved start-up entrepreneurs."),
      type("Residence Permit for Studies", "Study", "For eligible students admitted to Finnish degree, vocational or exchange programmes, subject to funds and insurance requirements."),
      type("Researcher Residence Permit", "Research", "For qualifying researchers carrying out research at an eligible host organization."),
      type("Family Ties Residence Permit", "Family reunification", "For eligible spouses, children, guardians and other qualifying family relationships."),
      type("Au Pair Residence Permit", "Cultural exchange / au pair", "For eligible young applicants participating in an au pair arrangement that meets Finnish requirements."),
      type("Working Holiday", "Youth mobility", "Available to eligible citizens of countries with working-holiday arrangements with Finland."),
      type("Permanent / Long-Term EU Residence", "Long-term residence", "Long-term status may be available after qualifying legal residence and other statutory conditions."),
    ],
  },
  {
    country: "Poland",
    slug: "poland",
    region: "Europe",
    authority: "Polish Ministry of Foreign Affairs / Office for Foreigners",
    officialUrl: "https://www.gov.pl/web/diplomacy/visas",
    overview: "Poland issues Schengen Type C visas for short stays and Type D national visas for longer stays. Long-term residence is then governed through temporary or permanent residence permits tied to work, study, family and other grounds.",
    entryNote: "A Polish national visa can authorize longer entry/stay, but the underlying right to work may also depend on a work permit, declaration or residence status. Applicants should distinguish visa, work authorization and residence permit requirements.",
    visaTypes: [
      type("Schengen Visa - Type C", "Short visits", "For stays up to 90 days in any 180-day period for tourism, family, business and other eligible short-stay purposes."),
      type("National Visa - Type D", "Long stay", "For stays exceeding 90 days, valid for a specified purpose and up to the statutory maximum validity period."),
      type("Work Visa / National Visa for Employment", "Employment entry", "Used by eligible workers who have the required work authorization or exemption and supporting employer documents."),
      type("Temporary Residence and Work Permit", "Longer-term employment", "Combined residence/work status for eligible foreigners employed in Poland."),
      type("EU Blue Card", "Highly qualified employment", "Residence/work route for eligible highly qualified workers meeting current qualification and salary requirements."),
      type("ICT / Intra-Corporate Transfer Permit", "Corporate transfer", "For eligible managers, specialists or trainees transferred within a corporate group."),
      type("Seasonal Work Route", "Seasonal employment", "Visa/work permit route for qualifying seasonal jobs under Polish labour rules."),
      type("Student Visa / Temporary Residence for Studies", "Study", "For full-time students admitted to qualifying Polish education programmes."),
      type("Business / Entrepreneur Residence", "Business activity", "Residence routes are available for qualifying foreigners conducting business activity and meeting economic requirements."),
      type("Family Reunification Residence", "Join qualifying family", "Residence permit for eligible family members of Polish citizens or qualifying foreign residents."),
      type("Permanent Residence / EU Long-Term Resident", "Long-term residence", "Permanent and EU long-term residence statuses are available to eligible applicants who meet the specific statutory grounds."),
    ],
  },
  {
    country: "Austria",
    slug: "austria",
    region: "Europe",
    authority: "Austrian Federal Government Migration Platform / Austrian diplomatic missions",
    officialUrl: "https://www.migration.gv.at/en/welcome/",
    overview: "Austria uses Schengen visas for short visits and national visas/residence titles for longer stays. Its main skilled immigration framework includes the Red-White-Red Card and EU Blue Card.",
    entryNote: "The exact route depends on qualifications, salary, occupation, points, employer and intended length of stay. Residence applications may involve Austrian representations, residence authorities and the Public Employment Service.",
    visaTypes: [
      type("Airport Transit Visa - Type A", "Airport transit", "For certain visa-required travellers transiting through an Austrian airport."),
      type("Schengen Visa - Type C", "Short visits", "For visits up to 90 days in any 180-day period for tourism, business, family and other permitted purposes."),
      type("National Visa - Type D", "Longer temporary stay", "For certain stays generally between 91 days and six months, depending on purpose and eligibility."),
      type("Red-White-Red Card - Very Highly Qualified Workers", "Highly qualified employment", "Points-based route for eligible very highly qualified workers."),
      type("Red-White-Red Card - Skilled Workers in Shortage Occupations", "Employment in shortage roles", "For eligible workers with qualifications and a qualifying job offer in a listed shortage occupation."),
      type("Red-White-Red Card - Other Key Workers", "Key employment", "For eligible key workers meeting points, salary and labour-market requirements."),
      type("Red-White-Red Card - Graduates", "Employment after Austrian study", "Route for eligible graduates of Austrian universities or universities of applied sciences who find qualifying employment."),
      type("Red-White-Red Card - Start-up Founders / Self-Employed Key Workers", "Entrepreneurship", "Business migration routes for eligible innovative founders and self-employed key workers meeting economic and points criteria."),
      type("EU Blue Card", "Highly qualified employment", "Residence/work title for eligible university-qualified workers with a qualifying Austrian job and salary."),
      type("Job Seeker Visa", "Job search by very highly qualified workers", "Allows eligible very highly qualified applicants to enter Austria for a limited period to seek qualifying employment."),
      type("Student Residence Permit", "Study", "For eligible third-country students admitted to qualifying Austrian educational institutions."),
      type("Researcher / ICT / Other Work Residence", "Research or specialized corporate work", "Additional residence titles apply to researchers, intra-corporate transferees and other defined employment situations."),
      type("Family Reunification / Red-White-Red Card Plus", "Join qualifying family", "Family members may qualify for specific residence titles with work access depending on the sponsor's status."),
    ],
  },
  {
    country: "Ireland",
    slug: "ireland",
    region: "Europe",
    authority: "Immigration Service Delivery / Department of Justice",
    officialUrl: "https://www.irishimmigration.ie/about-irish-visas/",
    overview: "Ireland is not part of the Schengen visa area. Irish visas are generally divided into short-stay Type C and long-stay Type D, with specific purposes such as work, study, family, business or visit.",
    entryNote: "A visa is permission to travel to Ireland and seek entry; it is not a guarantee of admission. Employment often requires a separate employment permit before a long-stay employment visa is issued.",
    visaTypes: [
      type("Short-Stay C Tourist Visa", "Tourism", "For visa-required visitors travelling for a short holiday or tourism stay of up to 90 days."),
      type("Short-Stay C Visit Family/Friend Visa", "Family or friend visit", "For short visits to relatives or friends in Ireland."),
      type("Short-Stay C Business Visa", "Business visit", "For permitted short business activity such as meetings or conferences, not ordinary Irish employment."),
      type("Short-Stay C Conference / Event / Performance", "Defined short professional or cultural activity", "For eligible conference, event, performance or other short purpose where the specific Irish rules are met."),
      type("Long-Stay D Employment Visa", "Employment", "For visa-required applicants coming to work after obtaining the required employment permit or qualifying exemption."),
      type("Critical Skills / General Employment Permit Pathway", "Employment permit basis", "Employment permits are separate from the visa. Eligible workers generally secure the correct permit before the D visa and residence process."),
      type("Long-Stay D Study Visa", "Study over 90 days", "For eligible students accepted onto qualifying Irish programmes and able to meet finance, insurance and other requirements."),
      type("Join Family Visa", "Family reunification", "Short- or long-stay family route depending on the relationship, sponsor and intended duration."),
      type("Volunteer / Minister of Religion / Other D Visas", "Specific long-stay purpose", "Long-stay routes exist for eligible volunteers, ministers of religion and other defined non-employment purposes."),
      type("Atypical Working Scheme", "Short specialized work", "Special permission for certain short-term work situations that fall outside ordinary employment permit arrangements."),
      type("Working Holiday Authorization", "Youth mobility", "Available to eligible nationals of participating countries under bilateral agreements."),
      type("Stamp-Based Residence Permissions", "Residence after entry", "After arrival, non-EEA nationals may receive immigration permissions such as Stamp 1, 1G, 2, 3 or 4 depending on work, study or family basis."),
    ],
  },
  {
    country: "Luxembourg",
    slug: "luxembourg",
    region: "Europe",
    authority: "Luxembourg Ministry of Foreign and European Affairs / General Department of Immigration",
    officialUrl: "https://mae.gouvernement.lu/en/services-aux-citoyens/visa-immigration.html",
    overview: "Luxembourg issues Schengen short-stay visas and national Type D visas for longer stays. Third-country nationals staying more than three months usually need authorization to stay before entry and then a residence permit after arrival.",
    entryNote: "For many long-stay categories, the sequence is authorization to stay, Type D visa if required, declaration of arrival, medical check where applicable, and residence permit application.",
    visaTypes: [
      type("Airport Transit Visa", "Airport transit", "For certain visa-required travellers transiting through the international area of an airport."),
      type("Schengen Short-Stay Visa - Type C", "Tourism, family, business and short visits", "For stays up to 90 days in any 180-day period. It can be single-entry or multiple-entry depending on the decision."),
      type("National Long-Stay Visa - Type D", "Long stay", "Entry visa for applicants approved for residence over 90 days when their nationality requires a visa."),
      type("Salaried Worker Residence", "Employment", "For qualifying third-country employees after labour-market and authorization-to-stay requirements are met."),
      type("EU Blue Card", "Highly qualified employment", "Residence route for eligible highly qualified workers meeting current qualification and salary conditions."),
      type("Self-Employed Residence", "Business or professional activity", "For qualifying self-employed applicants who meet business, economic and professional requirements."),
      type("Investor Residence", "Investment", "Residence route for qualifying investors under the applicable Luxembourg investment categories."),
      type("Student Residence", "Higher education", "For eligible full-time students admitted to qualifying Luxembourg higher-education institutions."),
      type("Researcher Residence", "Research", "For qualifying researchers hosted by eligible research organizations."),
      type("Trainee Residence", "Academic training / internship", "For eligible third-country trainees completing qualifying training linked to academic studies."),
      type("Family Reunification", "Join qualifying family", "Residence route for eligible family members of third-country nationals or other lawful residents under the applicable rules."),
      type("Private Reasons Residence", "Private residence on defined grounds", "Residence permit for qualifying private reasons where the legal and financial conditions are met."),
      type("Post-Study Job Search / Business Creation", "Transition after higher education", "Eligible graduates may qualify for temporary residence to seek employment or establish a business related to their studies."),
    ],
  },
];

export function getVisaGuide(slug: string) {
  return VISA_GUIDES.find((guide) => guide.slug === slug);
}
